<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yi Wang">

<title>NewJeans: Why Did They Explode?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-0b716d6fe31096b8dc5b1cb48462c79f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="index_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="index_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<link href="index_files/libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">

<script src="index_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<link href="index_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">

<script src="index_files/libs/datatables-binding-0.34.0/datatables.js"></script>

<script src="index_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>

<link href="index_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">

<link href="index_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">

<script src="index_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>

<link href="index_files/libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">

<script src="index_files/libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>

<link href="index_files/libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">

<script src="index_files/libs/selectize-0.12.0/selectize.min.js"></script>

<link href="index_files/libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">

<script src="index_files/libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>



</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#about" id="toc-about" class="nav-link active" data-scroll-target="#about">About</a></li>
  <li><a href="#full-corpus-explorer" id="toc-full-corpus-explorer" class="nav-link" data-scroll-target="#full-corpus-explorer">Full Corpus Explorer</a></li>
  <li><a href="#feature-comparison" id="toc-feature-comparison" class="nav-link" data-scroll-target="#feature-comparison">Feature Comparison</a></li>
  <li><a href="#chromagram-of-hype-boy" id="toc-chromagram-of-hype-boy" class="nav-link" data-scroll-target="#chromagram-of-hype-boy">Chromagram of “Hype Boy”</a></li>
  <li><a href="#self-similarity-matrices" id="toc-self-similarity-matrices" class="nav-link" data-scroll-target="#self-similarity-matrices">Self-Similarity Matrices</a></li>
  <li><a href="#tempogram-analysis" id="toc-tempogram-analysis" class="nav-link" data-scroll-target="#tempogram-analysis">Tempogram Analysis</a></li>
  <li><a href="#clustering" id="toc-clustering" class="nav-link" data-scroll-target="#clustering">Clustering</a></li>
  <li><a href="#summary-and-conclusion" id="toc-summary-and-conclusion" class="nav-link" data-scroll-target="#summary-and-conclusion">Summary and Conclusion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">NewJeans: Why Did They Explode?</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">A Computational Analysis of 4th Generation K-pop’s Paradigm Shift</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yi Wang </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<style type="text/css">
.parcoords line {
  stroke-opacity: 0.6;
}
.table-caption {
  margin-top: 10px;
  font-style: italic;
  text-align: center;
}
</style>
</div>
<section id="about" class="level2">
<h2 class="anchored" data-anchor-id="about">About</h2>
<section id="the-top-problem-in-4th-generation-k-pop" class="level3">
<h3 class="anchored" data-anchor-id="the-top-problem-in-4th-generation-k-pop">The “Top” Problem in 4th Generation K-pop</h3>
<p>In K-pop, there is a concept called <strong>“Top group</strong> ， which is when a group achieves overwhelming dominance across album sales, digital charts, public recognition, and cultural influence. From H.O.T (1st gen) to Girls’ Generation and BIGBANG (2nd gen), to BTS and TWICE (3rd gen), each era has had its undisputed top group.</p>
<p>But the 4th generation (groups debuting around 2018-2022) has a problem: no one has clearly reached the top. aespa, I-DLE, IVE, and LE SSERAFIM each have their strengths, unique concepts, self-production, elegant aesthetics, empowering messages, but none has achieved the kind of sweeping dominance seen in previous generations. Fans and critics often say: <em>“They’re all too different to choose one.”</em></p>
</section>
<section id="newjeans-a-meteoric-debut" class="level3">
<h3 class="anchored" data-anchor-id="newjeans-a-meteoric-debut">NewJeans: A “Meteoric” Debut</h3>
<p>Then came <strong>NewJeans</strong>. Debuting in July 2022 with minimal promotion and no fixed leader, they seemed to appear out of nowhere. Yet their debut tracks “Attention” and “Hype Boy” exploded across charts, and their “Y2K revival” aesthetic quickly became a cultural phenomenon.</p>
<p>This raises the question: <strong>Was their success accidental, or was there something fundamentally different about their music?</strong></p>
<p>This study uses computational musicology to analyze NewJeans’ audio features and compare them with other 4th generation girl groups, seeking to understand whether their “unique sound” contributed to their meteoric rise.</p>
</section>
<section id="about-this-study" class="level3">
<h3 class="anchored" data-anchor-id="about-this-study">About This Study</h3>
<p><strong>Research Question:</strong><br>
This study investigates why NewJeans, a 4th generation K-pop girl group, achieved rapid popularity despite debuting with minimal promotion. Specifically, it examines whether distinct audio features in their music—such as rhythm, timbre, harmonic structure, and overall sonic identity contributed to their meteoric rise compared to peer groups.</p>
<p><strong>Research Focus / Scope:</strong><br>
- Comparative analysis of <strong>58 title tracks</strong> from five 4th generation girl groups: NewJeans, aespa, (G)I-DLE, IVE, and LE SSERAFIM.<br>
- Examination of <strong>Spotify audio features</strong> including Danceability, Energy, Loudness, Acousticness, Instrumentalness, Liveness, Valence, Tempo, and Duration.<br>
- In-depth analysis of NewJeans’ breakout track <strong>“Hype Boy”</strong> using:<br>
- Chromagram (harmonic content)<br>
- Self-Similarity Matrices (structural repetition and timbre consistency)<br>
- Tempogram Analysis (novelty curves, autocorrelation, Fourier transform)<br>
- Clustering analysis to determine how closely NewJeans tracks are grouped based on audio features.</p>
<p><strong>Key Assumptions:</strong><br>
1. Audio features extracted from Spotify tracks are reliable proxies for the sonic characteristics that listeners perceive.<br>
2. Breakout success can be partially attributed to distinctive musical features, even though other factors (promotion, social media virality, visual aesthetics) play a role.<br>
3. Seed-based clustering assumes that representative tracks capture the core musical style of each group.<br>
4. Statistical and computational analyses can reveal patterns that correspond meaningfully to perceived uniqueness, memorability, and listener engagement.</p>
<p>This study combines <strong>computational musicology, statistical analysis, and music theory</strong> to explore how NewJeans’ musical identity distinguishes them within the competitive landscape of 4th generation K-pop.</p>
</section>
<section id="corpus" class="level3">
<h3 class="anchored" data-anchor-id="corpus">Corpus</h3>
<table class="table table-striped table-hover table-condensed caption-top">
<caption>Corpus: 5 Girl Groups, 58 Title Tracks</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Group</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Tracks</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Style Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">**NewJeans**</td>
<td style="text-align: center;">11</td>
<td style="text-align: right;">Y2K revival, lo-fi, UK garage, 'effortless'</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">aespa</td>
<td style="text-align: center;">12</td>
<td style="text-align: right;">Hyperpop, AI concept, futuristic</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(G)I-DLE</td>
<td style="text-align: center;">14</td>
<td style="text-align: right;">Self-produced, experimental, bold</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">IVE</td>
<td style="text-align: center;">12</td>
<td style="text-align: right;">Elegant, confident, luxurious</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">LE SSERAFIM</td>
<td style="text-align: center;">9</td>
<td style="text-align: right;">Self-empowerment, edgy, powerful</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> NewJeans is the focus of this analysis.</td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
<p><strong>Total: 58 title tracks</strong></p>
<hr>
</section>
</section>
<section id="full-corpus-explorer" class="level2">
<h2 class="anchored" data-anchor-id="full-corpus-explorer">Full Corpus Explorer</h2>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-86fb48ea46329801f313" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-86fb48ea46329801f313">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"90\" data-max=\"172\" data-scale=\"1\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.62\" data-max=\"0.974\" data-scale=\"3\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.384\" data-max=\"0.9\" data-scale=\"3\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.001\" data-max=\"0.653\" data-scale=\"3\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"-7.2\" data-max=\"-0.2\" data-scale=\"1\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.183\" data-max=\"0.968\" data-scale=\"3\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","caption":"<caption style=\"caption-side: bottom; text-align: center;\">Table 1: All 58 title tracks with Spotify audio features<\/caption>","data":[["aespa","aespa","aespa","aespa","aespa","aespa","aespa","aespa","aespa","aespa","aespa","aespa","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","(G)I-DLE","IVE","IVE","IVE","IVE","IVE","IVE","IVE","IVE","IVE","IVE","IVE","IVE","LE SSERAFIM","LE SSERAFIM","LE SSERAFIM","LE SSERAFIM","LE SSERAFIM","LE SSERAFIM","LE SSERAFIM","LE SSERAFIM","LE SSERAFIM","NewJeans","NewJeans","NewJeans","NewJeans","NewJeans","NewJeans","NewJeans","NewJeans","NewJeans","NewJeans","NewJeans"],["Black Mamba","Next Level","Savage","Illusion","Girls","Spicy","Drama","Supernova","Whiplash","Dirty Work","Rich Man","Armageddon","LATATA","HANN (Alone)","Senorita","Uh-Oh","Oh my god","DUMDi DUMDi","HWAA","TOMBOY","Nxde","Queencard","Klaxon","Good Thing","Super Lady","Mono (feat. skaiwater)","ELEVEN","LOVE DIVE","After LIKE","I AM","Kitsch","Baddie","해야 (HEYA)","Accendio","REBEL HEART","XOXZ","BANG BANG","BLACKHOLE","FEARLESS","ANTIFRAGILE","Perfect Night","EASY","HOT","UNFORGIVEN (feat. Nile Rodgers)","Smart","SPAGHETTI","CRAZY","Attention","Hype Boy","OMG","Super Shy","New Jeans","Cool With You","Bubble Gum","How Sweet","Supernatural","Ditto","ETA"],[90.09999999999999,109,147,90,172,114.9,131,120.1,126,98,110,92,98.09999999999999,105,120,92,110,123,95,124,136.1,130,120,132,121.9,114.9,120,117.9,125,122,102,160,92,140,128,98,152.2,125.9,104,105,136.1,165,128,104,113.1,111.5,130,105,100,127,149.9,134,135,105,125,108.9,133.9,135],[0.915,0.852,0.879,0.718,0.974,0.898,0.872,0.747,0.9,0.738,0.92,0.789,0.792,0.718,0.8080000000000001,0.8139999999999999,0.762,0.914,0.868,0.871,0.912,0.832,0.888,0.9379999999999999,0.869,0.734,0.731,0.709,0.922,0.875,0.792,0.678,0.837,0.875,0.777,0.787,0.908,0.911,0.62,0.797,0.82,0.7,0.63,0.875,0.675,0.819,0.899,0.648,0.9350000000000001,0.771,0.8169999999999999,0.721,0.65,0.709,0.895,0.708,0.641,0.749],[0.52,0.82,0.727,0.75,0.57,0.757,0.644,0.744,0.863,0.748,0.732,0.695,0.774,0.709,0.782,0.781,0.794,0.759,0.384,0.756,0.728,0.819,0.891,0.6840000000000001,0.795,0.779,0.828,0.703,0.68,0.6830000000000001,0.8,0.736,0.702,0.759,0.677,0.784,0.628,0.66,0.863,0.882,0.697,0.744,0.763,0.795,0.799,0.9,0.802,0.8110000000000001,0.593,0.804,0.776,0.8070000000000001,0.752,0.758,0.803,0.699,0.8139999999999999,0.8120000000000001],[0.062,0.488,0.124,0.081,0.115,0.014,0.164,0.007,0.095,0.289,0.08799999999999999,0.065,0.004,0.059,0.016,0.059,0.036,0.025,0.046,0.01,0.039,0.032,0.13,0.001,0.093,0.036,0.062,0.004,0.103,0.012,0.012,0.046,0.03,0.049,0.018,0.032,0.011,0.109,0.051,0.082,0.1,0.189,0.08799999999999999,0.111,0.115,0.081,0.01,0.236,0.268,0.357,0.18,0.51,0.653,0.138,0.082,0.185,0.027,0.108],[-2.9,-2.6,-1.2,-2.8,-0.2,-1.2,-1.5,-4.3,-3,-5,-2.5,-2,-4,-3.3,-3.1,-3.3,-3.5,-1.1,-3.2,-2.4,-2,-2.8,-3.4,-2.1,-4.5,-6.7,-3,-4.2,-1.2,-4.9,-5,-4.5,-3.4,-3.9,-4.8,-5.2,-3.1,-4,-7.2,-3.3,-4.5,-5.2,-3.4,-4.1,-5.5,-4.6,-2.2,-3.7,-3.4,-4.1,-6,-6.2,-6.7,-3.6,-2.9,-4.2,-6,-6.4],[0.5,0.82,0.671,0.592,0.65,0.842,0.378,0.368,0.748,0.631,0.673,0.469,0.505,0.24,0.42,0.782,0.482,0.674,0.233,0.644,0.651,0.669,0.801,0.93,0.528,0.391,0.587,0.538,0.799,0.384,0.455,0.757,0.6850000000000001,0.662,0.531,0.486,0.374,0.345,0.432,0.824,0.502,0.602,0.968,0.375,0.594,0.872,0.531,0.695,0.783,0.739,0.515,0.532,0.532,0.529,0.757,0.863,0.183,0.841]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>Group<\/th>\n      <th>Track Name<\/th>\n      <th>Tempo<\/th>\n      <th>Energy<\/th>\n      <th>Danceability<\/th>\n      <th>Acousticness<\/th>\n      <th>Loudness<\/th>\n      <th>Valence<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":15,"order":[[0,"asc"]],"columnDefs":[{"className":"dt-right","targets":[2,3,4,5,6,7]},{"name":"Group","targets":0},{"name":"Track Name","targets":1},{"name":"Tempo","targets":2},{"name":"Energy","targets":3},{"name":"Danceability","targets":4},{"name":"Acousticness","targets":5},{"name":"Loudness","targets":6},{"name":"Valence","targets":7}],"autoWidth":false,"orderClasses":false,"orderCellsTop":true,"lengthMenu":[10,15,25,50,100],"rowCallback":"function(row, data, displayNum, displayIndex, dataIndex) {\nvar value=data[0]; $(row).css({'background-color':value == \"NewJeans\" ? \"#FFF9E6\" : null});\n}"}},"evals":["options.rowCallback"],"jsHooks":[]}</script>
</div>
</div>
<hr>
</section>
<section id="feature-comparison" class="level2">
<h2 class="anchored" data-anchor-id="feature-comparison">Feature Comparison</h2>
<section id="parallel-coordinates-plot" class="level3">
<h3 class="anchored" data-anchor-id="parallel-coordinates-plot">Parallel Coordinates Plot</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/parallel-coords-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exact-values" class="level3">
<h3 class="anchored" data-anchor-id="exact-values">Exact Values</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>NEWJEANS FEATURE VALUES (Normalized 0-1)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  Feature      NewJeans
  &lt;chr&gt;           &lt;dbl&gt;
1 Acousticness    0.249
2 Energy          0.749
3 Tempo           0.635
4 Loudness        0.759
5 Valence         0.634
6 Danceability    0.766</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>ALL GROUPS COMPARISON</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  Feature      `(G)I-DLE`    IVE `LE SSERAFIM` NewJeans aespa
  &lt;chr&gt;             &lt;dbl&gt;  &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
1 Acousticness     0.0417 0.0405        0.0919    0.249 0.133
2 Energy           0.837  0.817         0.759     0.749 0.850
3 Tempo            0.559  0.636         0.618     0.635 0.567
4 Loudness         0.838  0.803         0.778     0.759 0.879
5 Valence          0.568  0.550         0.633     0.634 0.612
6 Danceability     0.745  0.72          0.805     0.766 0.714</code></pre>
</div>
</div>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<p>Based on the exact values above:</p>
<p><strong>1. Acousticness = 0.249 — Highest among all groups</strong></p>
<p>NewJeans scores significantly higher in acousticness than any other group (next closest is aespa at 0.133). This means their music relies more on organic instruments—guitars, live drums, natural reverb—rather than synthetic sounds. This is the sonic foundation of their “warm, nostalgic” Y2K aesthetic.</p>
<p><strong>2. Energy = 0.749 — Lowest among all groups</strong></p>
<p>While other groups range from 0.759 to 0.850, NewJeans sits at the bottom. This low energy is the source of their signature “effortless” feel. They don’t need to be loud or aggressive to capture attention. The music breathes rather than pushes.</p>
<p><strong>3. Tempo = 0.635 — Highest (tied with IVE)</strong></p>
<p>This creates a unique paradox: <strong>fastest tempo + lowest energy = rushing but relaxed</strong>. The fast beat provides forward momentum, but the low energy keeps it from feeling frantic. This is the essence of “chill but danceable.”</p>
<p><strong>4. Loudness = 0.759 — Weakest among all groups</strong></p>
<p>NewJeans is the quietest group. Their music preserves more dynamic range—quieter verses, fuller choruses—creating a more intimate, breathing listening experience. They don’t need to be loud to be heard.</p>
<p><strong>5. Valence = 0.634 — Highest (tied with LE SSERAFIM)</strong></p>
<p>NewJeans’ music feels the most positive and joyful. This high valence, combined with high acousticness, creates a warm, nostalgic emotional palette—music that sounds like a fond memory rather than a present scream.</p>
<p><strong>6. Danceability = 0.766 — 2nd Highest (behind LE SSERAFIM at 0.805)</strong></p>
<p>Despite having the lowest energy and quietest dynamics, NewJeans ranks second in danceability. This is the signature of <strong>syncopated rhythm</strong> (UK garage / 2-step influence). You can dance not because the music is loud or fast, but because the groove is infectious.</p>
</section>
</section>
<section id="chromagram-of-hype-boy" class="level2">
<h2 class="anchored" data-anchor-id="chromagram-of-hype-boy">Chromagram of “Hype Boy”</h2>
<p>For this analysis, I selected <strong>“Hype Boy”</strong> — NewJeans’ debut title track and their first breakout hit. Released in July 2022, this song introduced the group’s signature sound to the world and became an instant viral sensation. As a debut track that defined a group’s identity, “Hype Boy” serves as an ideal case study for understanding the musical DNA that made NewJeans stand out. I chose to focus on a single representative song because each group’s core style is most clearly expressed in their breakout hit, which captures the essence of what makes them unique.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Chromagram dimensions: 3860 13 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Column names: TIME, A, Bb, B, C, C., D, Eb, E, F, F., G, Ab </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/plot-chroma-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>AVERAGE CHROMA INTENSITY BY PITCH</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    C    C#     D    D#     E     F    F#     G    G#     A    A#     B 
1.103 0.225 1.564 0.643 0.253 1.105 0.165 1.307 0.280 0.721 1.234 0.313 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Strongest pitch classes:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  D: 1.564
  G: 1.307
  A#: 1.234</code></pre>
</div>
</div>
<section id="analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="analysis-1">Analysis</h3>
<p>Looking at the chromagram data, three pitch classes stand out clearly: D (1.564), G (1.307), and A# (1.234). Everything else like F# at 0.165 and C# at 0.225 is much weaker. This tells us that “Hype Boy” has a clear harmonic center around D, with G and A# playing important supporting roles. What’s interesting is the A#. In a typical major key, you’d expect A natural (the dominant), not A#. That flat 7th gives the song a slightly different color, not dramatically strange, but just enough to make it feel less predictable than standard pop. The other pitch classes are so low that the harmonic content feels focused and repetitive, which matches what we hear in the track: a smooth, hypnotic groove that doesn’t jump around between different keys or throw in unexpected surprises. So overall, “Hype Boy” isn’t harmonically complex or ambiguous, it’s actually very consistent, built around a stable D-centered framework with a few carefully chosen pitches (G and A#) that give it its recognizable character.</p>
</section>
</section>
<section id="self-similarity-matrices" class="level2">
<h2 class="anchored" data-anchor-id="self-similarity-matrices">Self-Similarity Matrices</h2>
<p>Self-similarity matrices (SSM) reveal how different sections of a song relate to each other. A dark diagonal line represents self-identity (a moment compared to itself). Patterns off the diagonal show repetition — for example, if the chorus sounds similar to the verse, those time regions will appear as bright blocks.</p>
<p>For this analysis, I generated two SSMs for “Hype Boy”: one using <strong>chroma features</strong> (harmonic content) and one using <strong>MFCC features</strong> (timbre / texture).</p>
<section id="chroma-self-similarity-matrix" class="level3">
<h3 class="anchored" data-anchor-id="chroma-self-similarity-matrix">Chroma Self-Similarity Matrix</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/load-chroma-ssm-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mfcc-self-similarity-matrix-timbre" class="level3">
<h3 class="anchored" data-anchor-id="mfcc-self-similarity-matrix-timbre">MFCC Self-Similarity Matrix (Timbre)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/load-mfcc-ssm-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analysis-2" class="level3">
<h3 class="anchored" data-anchor-id="analysis-2">Analysis</h3>
<p><strong>Chroma SSM (Harmonic Structure)</strong></p>
<p>The Chroma SSM reveals strong harmonic repetition throughout “Hype Boy.” The regular block patterns off the diagonal indicate that the song’s chord progressions repeat in a predictable, cyclical manner. Verses and choruses share similar harmonic materials, meaning the song relies on repeated and stable chord loops rather than dramatic harmonic shifts.</p>
<p><strong>MFCC SSM (Timbre / Texture)</strong></p>
<p>The MFCC SSM shows highly consistent timbre across the entire track. The uniformly bright colors indicate that the song’s instrumentation, vocal layering, and production texture remain stable from beginning to end. There are no sudden changes in sound design or abrupt stylistic shifts.</p>
<p>Together, these two matrices reveal a deliberate production strategy. The Chroma SSM shows high structural repetition, which helps listeners remember the song quickly. The MFCC SSM shows timbral consistency, which creates a smooth, low-cognitive-load listening experience that is easy to replay.</p>
<p>This combination of harmonic repetition and timbral stability produces a listening experience that feels cohesive, effortless, and loop-friendly. There is no sudden tension, no jarring contrast, and no unexpected complexity.</p>
<p><strong>Why This Matters for “Hype Boy”</strong></p>
<p>This balance between structural repetition and timbral stability reflects a modern production strategy where emotional continuity and replayability are prioritized over dramatic contrast. It helps explain why “Hype Boy” became widely popular: it is easy to remember, comfortable to listen to, and well-suited for streaming and short-form video platforms.</p>
<p>The chroma SSM reveals strong harmonic repetition, while the MFCC SSM shows highly consistent timbre across the track. Together, these features create a smooth, cohesive, and highly memorable listening experience, which helps explain why “Hype Boy” became widely popular.</p>
</section>
</section>
<section id="tempogram-analysis" class="level2">
<h2 class="anchored" data-anchor-id="tempogram-analysis">Tempogram Analysis</h2>
<section id="novelty-curve" class="level3">
<h3 class="anchored" data-anchor-id="novelty-curve">Novelty Curve</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/novelty-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The novelty function reveals the temporal distribution of structural changes throughout Hype Boy. Several prominent peaks appear around 20–40 seconds and 100–120 seconds, indicating moments of relatively stronger musical transitions. However, the curve is not dominated by dense or frequent high peaks; instead, it shows a continuous presence of smaller fluctuations across the entire track. This suggests that the song does not rely on abrupt or high-intensity contrasts (e.g., dramatic “drops”) to create interest. Rather, it employs a gradual and layered progression, where changes in texture, instrumentation, or rhythmic density accumulate over time. As a result, the listening experience is perceived as smooth and flowing, with a sense of ongoing motion rather than interruption. This type of structural design supports sustained engagement and contributes to the song’s high replayability.</p>
</section>
<section id="autocorrelation-tempogram-act" class="level3">
<h3 class="anchored" data-anchor-id="autocorrelation-tempogram-act">Autocorrelation Tempogram (ACT)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/act-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The autocorrelation tempogram highlights a stable and clearly defined periodic pulse, with the strongest energy concentrated around approximately 50 BPM, alongside its metrical multiples (e.g., 100 and 150 BPM). This indicates the presence of a consistent underlying beat that is perceptually salient to listeners. Such a structure facilitates embodied entrainment: listeners can easily synchronize bodily movement (e.g., head nodding or swaying) with the music. At the same time, the visibility of multiple metrical layers suggests the coexistence of both primary beats and finer rhythmic subdivisions. This combination is characteristic of groove-oriented styles such as R&amp;B and UK garage, where rhythmic subtlety coexists with overall stability. In Hype Boy, this results in a rhythmic feel that is not forceful or aggressive, but instead light, elastic, and naturally engaging. The groove is strong without being overwhelming, encouraging repeated listening through physical familiarity and comfort.</p>
</section>
<section id="fourier-tempogram-dft" class="level3">
<h3 class="anchored" data-anchor-id="fourier-tempogram-dft">Fourier Tempogram (DFT)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/dft-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The Fourier tempogram further emphasizes the periodic organization of rhythmic elements in the track. Distinct horizontal bands are visible around several tempo-related frequency regions (e.g., approximately 150, 250, and 400), indicating strong and persistent periodicities. These patterns demonstrate that the rhythmic structure is not random or densely layered, but rather organized into clear, repeating cycles. Notably, the intensity of these bands increases in specific sections (again around 20–40 seconds and 100–115 seconds), suggesting moments where rhythmic energy is selectively reinforced. This indicates that the song’s “hook” is not solely melodic but also rhythmic. The listener is not only remembering a tune, but also internalizing a recurring rhythmic pattern. Such periodic clarity enhances memorability while maintaining a sense of continuity, avoiding the need for abrupt structural contrasts.</p>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>Taken together, these three representations suggest that Hype Boy is built upon a foundation of rhythmic stability combined with gradual, fine-grained variation. The novelty function shows that structural change is distributed and controlled rather than explosive; the autocorrelation tempogram reveals a steady and easily internalized pulse; and the Fourier tempogram confirms the presence of clear and repetitive rhythmic cycles. This combination results in a listening experience that is smooth, lightweight, and highly loopable. Instead of relying on high-intensity contrasts typical of mainstream K-pop, the track emphasizes continuity, groove, and subtle evolution. From a stylistic perspective, this aligns closely with NewJeans’ broader aesthetic: understated, natural, and grounded in everyday listening contexts. Such a design is particularly well-suited to contemporary music consumption environments, where replayability, background listening, and short-form media integration are crucial. The balance between recognizability and low perceptual load allows the track to be both distinctive and non-fatiguing, helping to explain its widespread appeal and viral succes</p>
</section>
</section>
<section id="clustering" class="level2">
<h2 class="anchored" data-anchor-id="clustering">Clustering</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Total songs: 58 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Group distribution:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
                   aespa                    i-dle          i-dle;skaiwater 
                      12                       13                        1 
                     IVE              LE SSERAFIM       LE SSERAFIM;j-hope 
                      12                        7                        1 
LE SSERAFIM;Nile Rodgers                 NewJeans 
                       1                       11 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Seed songs (5 NewJeans tracks):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  1. Hype Boy
  2. OMG
  3. Super Shy
  4. How Sweet
  5. Ditto</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/clustering-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Found 5 seed songs:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  ✓ Hype Boy 
  ✓ OMG 
  ✓ Super Shy 
  ✓ How Sweet 
  ✓ Ditto </code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 20 Songs Closest to Seed Tracks</caption>
<colgroup>
<col style="width: 31%">
<col style="width: 31%">
<col style="width: 8%">
<col style="width: 4%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">song</th>
<th style="text-align: right;">distance</th>
<th style="text-align: right;">rank</th>
<th style="text-align: left;">group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Accendio</td>
<td style="text-align: left;">Accendio</td>
<td style="text-align: right;">1.743209</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">IVE</td>
</tr>
<tr class="even">
<td style="text-align: left;">REBEL HEART</td>
<td style="text-align: left;">REBEL HEART</td>
<td style="text-align: right;">1.940038</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">IVE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Super Lady</td>
<td style="text-align: left;">Super Lady</td>
<td style="text-align: right;">2.027332</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">i-dle</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dirty Work</td>
<td style="text-align: left;">Dirty Work</td>
<td style="text-align: right;">2.044586</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">aespa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ELEVEN</td>
<td style="text-align: left;">ELEVEN</td>
<td style="text-align: right;">2.152525</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">IVE</td>
</tr>
<tr class="even">
<td style="text-align: left;">BLACKHOLE</td>
<td style="text-align: left;">BLACKHOLE</td>
<td style="text-align: right;">2.186829</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">IVE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oh my god</td>
<td style="text-align: left;">Oh my god</td>
<td style="text-align: right;">2.190447</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">i-dle</td>
</tr>
<tr class="even">
<td style="text-align: left;">TOMBOY</td>
<td style="text-align: left;">TOMBOY</td>
<td style="text-align: right;">2.228963</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">i-dle</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bubble Gum</td>
<td style="text-align: left;">Bubble Gum</td>
<td style="text-align: right;">2.250041</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">NewJeans</td>
</tr>
<tr class="even">
<td style="text-align: left;">Supernova</td>
<td style="text-align: left;">Supernova</td>
<td style="text-align: right;">2.256114</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">aespa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UNFORGIVEN (feat. Nile Rodgers)</td>
<td style="text-align: left;">UNFORGIVEN (feat. Nile Rodgers)</td>
<td style="text-align: right;">2.268719</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">LE SSERAFIM;Nile Rodgers</td>
</tr>
<tr class="even">
<td style="text-align: left;">Super Shy</td>
<td style="text-align: left;">Super Shy</td>
<td style="text-align: right;">2.285651</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">NewJeans</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OMG</td>
<td style="text-align: left;">OMG</td>
<td style="text-align: right;">2.287230</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">NewJeans</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rich Man</td>
<td style="text-align: left;">Rich Man</td>
<td style="text-align: right;">2.354296</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">aespa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">How Sweet</td>
<td style="text-align: left;">How Sweet</td>
<td style="text-align: right;">2.362155</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">NewJeans</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perfect Night</td>
<td style="text-align: left;">Perfect Night</td>
<td style="text-align: right;">2.365986</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">LE SSERAFIM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I AM</td>
<td style="text-align: left;">I AM</td>
<td style="text-align: right;">2.394715</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">IVE</td>
</tr>
<tr class="even">
<td style="text-align: left;">Supernatural</td>
<td style="text-align: left;">Supernatural</td>
<td style="text-align: right;">2.478275</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">NewJeans</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Smart</td>
<td style="text-align: left;">Smart</td>
<td style="text-align: right;">2.486825</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">LE SSERAFIM</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kitsch</td>
<td style="text-align: left;">Kitsch</td>
<td style="text-align: right;">2.528998</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">IVE</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>The model shows moderate ability to identify NewJeans songs. The first correct retrieval appears relatively early, but overall recall remains limited. This suggests that while NewJeans songs share some common audio features, their feature space overlaps substantially with other K-pop groups, making precise clustering challenging.</p>
</section>
</section>
<section id="summary-and-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="summary-and-conclusion">Summary and Conclusion</h2>
<p>This computational analysis of NewJeans and other 4th generation K-pop girl groups provides several key insights into why NewJeans achieved rapid popularity despite debuting with minimal promotion.</p>
<p><strong>Corpus-Level Observations:</strong><br>
- Across 58 title tracks from five groups, NewJeans stands out for its high acousticness, moderate energy, and elevated danceability.<br>
- Their music balances organic instrumentation (guitars, natural reverb) with approachable tempos, creating a warm, nostalgic, and effortlessly engaging sonic identity.<br>
- Compared to peers, NewJeans occupies a distinctive feature space that emphasizes groove and subtle rhythmic complexity rather than loud, high-energy dynamics.</p>
<p><strong>Track-Level Analyses:</strong><br>
- <strong>Chromagram of “Hype Boy”</strong> shows a stable harmonic center around D, with supporting pitches G and A# adding color without introducing unpredictability.<br>
- <strong>Self-Similarity Matrices (SSMs)</strong> reveal high structural repetition and timbral consistency, indicating deliberate production choices that favor replayability and listener comfort.<br>
- <strong>Tempogram Analysis</strong> demonstrates rhythmic stability:<br>
- The novelty curve shows gradual structural changes rather than abrupt contrasts.<br>
- Autocorrelation tempograms highlight a clear underlying beat and its metrical multiples, promoting embodied entrainment.<br>
- Fourier tempograms emphasize recurring rhythmic cycles that reinforce memorability without relying on melodic hooks alone.</p>
<p><strong>Clustering Insights:</strong><br>
- Using audio feature clustering, the model successfully identifies NewJeans seed songs and ranks them closely among other tracks.<br>
- While the first correct retrieval appears early, overall recall is moderate, indicating that although NewJeans shares some features with other groups, their combination of acoustic warmth, moderate energy, and rhythmic subtlety is distinctive enough to be recognized computationally.</p>
<p><strong>Overall Conclusion:</strong><br>
NewJeans’ meteoric rise appears rooted in a carefully calibrated musical identity: their tracks are stylistically cohesive, rhythmically clear, harmonically stable, and emotionally warm. These qualities make the music easily recognizable, comfortable to listen to repeatedly, and highly engaging across streaming and short-form media platforms. From a computational perspective, their audio features position them uniquely among 4th generation girl groups, offering a plausible explanation for their rapid success and cultural impact.<br>
—</p>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "NewJeans: Why Did They Explode?"</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "A Computational Analysis of 4th Generation K-pop's Paradigm Shift"</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Yi Wang"</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> </span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 2</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: flatly</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: false</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co">    self-contained: false</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: false</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{css, echo=FALSE}</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="op">.</span><span class="fu">parcoords</span> line <span class="op">{</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>  stroke<span class="op">-</span>opacity<span class="op">:</span> <span class="fl">0.6</span><span class="op">;</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="op">.</span><span class="fu">table</span><span class="op">-</span>caption <span class="op">{</span></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>  margin<span class="op">-</span>top<span class="op">:</span> <span class="dv">10</span>px<span class="op">;</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>  font<span class="op">-</span>style<span class="op">:</span> italic<span class="op">;</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>  text<span class="op">-</span>align<span class="op">:</span> center<span class="op">;</span></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data and packages</span></span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dendextend)</span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a><span class="co"># read data</span></span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a>df_all <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/5K.csv"</span>)</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a>df_aespa <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Aespa_title.csv"</span>)</span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a>df_idle <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Idle_title.csv"</span>)</span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a>df_ive <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Ive_title.csv"</span>)</span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a>df_lesserafim <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Lesserafim_title.csv"</span>)</span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a>df_njs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/NJS_title.csv"</span>)</span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a>df_test <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/NJS_test.csv"</span>)</span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-49"><a href="#cb18-49" aria-hidden="true" tabindex="-1"></a><span class="co"># add group label</span></span>
<span id="cb18-50"><a href="#cb18-50" aria-hidden="true" tabindex="-1"></a>df_aespa<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="st">"aespa"</span></span>
<span id="cb18-51"><a href="#cb18-51" aria-hidden="true" tabindex="-1"></a>df_idle<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="st">"(G)I-DLE"</span></span>
<span id="cb18-52"><a href="#cb18-52" aria-hidden="true" tabindex="-1"></a>df_ive<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="st">"IVE"</span></span>
<span id="cb18-53"><a href="#cb18-53" aria-hidden="true" tabindex="-1"></a>df_lesserafim<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="st">"LE SSERAFIM"</span></span>
<span id="cb18-54"><a href="#cb18-54" aria-hidden="true" tabindex="-1"></a>df_njs<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="st">"NewJeans"</span></span>
<span id="cb18-55"><a href="#cb18-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-56"><a href="#cb18-56" aria-hidden="true" tabindex="-1"></a><span class="co"># combine all data</span></span>
<span id="cb18-57"><a href="#cb18-57" aria-hidden="true" tabindex="-1"></a>df_combined <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(df_aespa, df_idle, df_ive, df_lesserafim, df_njs)</span>
<span id="cb18-58"><a href="#cb18-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-59"><a href="#cb18-59" aria-hidden="true" tabindex="-1"></a><span class="co"># feature</span></span>
<span id="cb18-60"><a href="#cb18-60" aria-hidden="true" tabindex="-1"></a>feature_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Acousticness"</span>, <span class="st">"Energy"</span>, <span class="st">"Tempo"</span>, <span class="st">"Loudness"</span>, <span class="st">"Valence"</span>, <span class="st">"Danceability"</span>)</span>
<span id="cb18-61"><a href="#cb18-61" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-62"><a href="#cb18-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-63"><a href="#cb18-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## About</span></span>
<span id="cb18-64"><a href="#cb18-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-65"><a href="#cb18-65" aria-hidden="true" tabindex="-1"></a><span class="fu">### The "Top" Problem in 4th Generation K-pop</span></span>
<span id="cb18-66"><a href="#cb18-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-67"><a href="#cb18-67" aria-hidden="true" tabindex="-1"></a>In K-pop, there is a concept called **"Top group** ， which is when a group achieves overwhelming dominance across album sales, digital charts, public recognition, and cultural influence. From H.O.T (1st gen) to Girls' Generation and BIGBANG (2nd gen), to BTS and TWICE (3rd gen), each era has had its undisputed top group.</span>
<span id="cb18-68"><a href="#cb18-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-69"><a href="#cb18-69" aria-hidden="true" tabindex="-1"></a>But the 4th generation (groups debuting around 2018-2022) has a problem: no one has clearly reached the top. aespa, I-DLE, IVE, and LE SSERAFIM each have their strengths, unique concepts, self-production, elegant aesthetics, empowering messages, but none has achieved the kind of sweeping dominance seen in previous generations. Fans and critics often say: *"They're all too different to choose one."*</span>
<span id="cb18-70"><a href="#cb18-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-71"><a href="#cb18-71" aria-hidden="true" tabindex="-1"></a><span class="fu">### NewJeans: A "Meteoric" Debut</span></span>
<span id="cb18-72"><a href="#cb18-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-73"><a href="#cb18-73" aria-hidden="true" tabindex="-1"></a>Then came **NewJeans**. Debuting in July 2022 with minimal promotion and no fixed leader, they seemed to appear out of nowhere. Yet their debut tracks "Attention" and "Hype Boy" exploded across charts, and their "Y2K revival" aesthetic quickly became a cultural phenomenon.</span>
<span id="cb18-74"><a href="#cb18-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-75"><a href="#cb18-75" aria-hidden="true" tabindex="-1"></a>This raises the question: **Was their success accidental, or was there something fundamentally different about their music?**</span>
<span id="cb18-76"><a href="#cb18-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-77"><a href="#cb18-77" aria-hidden="true" tabindex="-1"></a>This study uses computational musicology to analyze NewJeans' audio features and compare them with other 4th generation girl groups, seeking to understand whether their "unique sound" contributed to their meteoric rise.</span>
<span id="cb18-78"><a href="#cb18-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-79"><a href="#cb18-79" aria-hidden="true" tabindex="-1"></a><span class="fu">### About This Study</span></span>
<span id="cb18-80"><a href="#cb18-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-81"><a href="#cb18-81" aria-hidden="true" tabindex="-1"></a>**Research Question:**  </span>
<span id="cb18-82"><a href="#cb18-82" aria-hidden="true" tabindex="-1"></a>This study investigates why NewJeans, a 4th generation K-pop girl group, achieved rapid popularity despite debuting with minimal promotion. Specifically, it examines whether distinct audio features in their music—such as rhythm, timbre, harmonic structure, and overall sonic identity contributed to their meteoric rise compared to peer groups.</span>
<span id="cb18-83"><a href="#cb18-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-84"><a href="#cb18-84" aria-hidden="true" tabindex="-1"></a>**Research Focus / Scope:**  </span>
<span id="cb18-85"><a href="#cb18-85" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Comparative analysis of **58 title tracks** from five 4th generation girl groups: NewJeans, aespa, (G)I-DLE, IVE, and LE SSERAFIM.  </span>
<span id="cb18-86"><a href="#cb18-86" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Examination of **Spotify audio features** including Danceability, Energy, Loudness, Acousticness, Instrumentalness, Liveness, Valence, Tempo, and Duration.  </span>
<span id="cb18-87"><a href="#cb18-87" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>In-depth analysis of NewJeans’ breakout track **“Hype Boy”** using:  </span>
<span id="cb18-88"><a href="#cb18-88" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Chromagram (harmonic content)  </span>
<span id="cb18-89"><a href="#cb18-89" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Self-Similarity Matrices (structural repetition and timbre consistency)  </span>
<span id="cb18-90"><a href="#cb18-90" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Tempogram Analysis (novelty curves, autocorrelation, Fourier transform)  </span>
<span id="cb18-91"><a href="#cb18-91" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Clustering analysis to determine how closely NewJeans tracks are grouped based on audio features.  </span>
<span id="cb18-92"><a href="#cb18-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-93"><a href="#cb18-93" aria-hidden="true" tabindex="-1"></a>**Key Assumptions:**  </span>
<span id="cb18-94"><a href="#cb18-94" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Audio features extracted from Spotify tracks are reliable proxies for the sonic characteristics that listeners perceive.  </span>
<span id="cb18-95"><a href="#cb18-95" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Breakout success can be partially attributed to distinctive musical features, even though other factors (promotion, social media virality, visual aesthetics) play a role.  </span>
<span id="cb18-96"><a href="#cb18-96" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Seed-based clustering assumes that representative tracks capture the core musical style of each group.  </span>
<span id="cb18-97"><a href="#cb18-97" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Statistical and computational analyses can reveal patterns that correspond meaningfully to perceived uniqueness, memorability, and listener engagement.  </span>
<span id="cb18-98"><a href="#cb18-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-99"><a href="#cb18-99" aria-hidden="true" tabindex="-1"></a>This study combines **computational musicology, statistical analysis, and music theory** to explore how NewJeans’ musical identity distinguishes them within the competitive landscape of 4th generation K-pop.</span>
<span id="cb18-100"><a href="#cb18-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-101"><a href="#cb18-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-102"><a href="#cb18-102" aria-hidden="true" tabindex="-1"></a><span class="fu">### Corpus</span></span>
<span id="cb18-103"><a href="#cb18-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-104"><a href="#cb18-104" aria-hidden="true" tabindex="-1"></a><span class="in">```{r corpus-table, results='asis'}</span></span>
<span id="cb18-105"><a href="#cb18-105" aria-hidden="true" tabindex="-1"></a><span class="co"># columns data</span></span>
<span id="cb18-106"><a href="#cb18-106" aria-hidden="true" tabindex="-1"></a>corpus_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-107"><a href="#cb18-107" aria-hidden="true" tabindex="-1"></a>  <span class="at">Group =</span> <span class="fu">c</span>(<span class="st">"**NewJeans**"</span>, <span class="st">"aespa"</span>, <span class="st">"(G)I-DLE"</span>, <span class="st">"IVE"</span>, <span class="st">"LE SSERAFIM"</span>),</span>
<span id="cb18-108"><a href="#cb18-108" aria-hidden="true" tabindex="-1"></a>  <span class="at">Tracks =</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">12</span>, <span class="dv">9</span>),</span>
<span id="cb18-109"><a href="#cb18-109" aria-hidden="true" tabindex="-1"></a>  <span class="at">Style =</span> <span class="fu">c</span>(<span class="st">"Y2K revival, lo-fi, UK garage, 'effortless'"</span>,</span>
<span id="cb18-110"><a href="#cb18-110" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Hyperpop, AI concept, futuristic"</span>,</span>
<span id="cb18-111"><a href="#cb18-111" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Self-produced, experimental, bold"</span>,</span>
<span id="cb18-112"><a href="#cb18-112" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Elegant, confident, luxurious"</span>,</span>
<span id="cb18-113"><a href="#cb18-113" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Self-empowerment, edgy, powerful"</span>)</span>
<span id="cb18-114"><a href="#cb18-114" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-115"><a href="#cb18-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-116"><a href="#cb18-116" aria-hidden="true" tabindex="-1"></a><span class="co"># use kableExtra to make columns</span></span>
<span id="cb18-117"><a href="#cb18-117" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(corpus_df, </span>
<span id="cb18-118"><a href="#cb18-118" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Corpus: 5 Girl Groups, 58 Title Tracks"</span>,</span>
<span id="cb18-119"><a href="#cb18-119" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="st">"lcr"</span>,</span>
<span id="cb18-120"><a href="#cb18-120" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Tracks"</span>, <span class="st">"Style Description"</span>),</span>
<span id="cb18-121"><a href="#cb18-121" aria-hidden="true" tabindex="-1"></a>      <span class="at">escape =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-122"><a href="#cb18-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>),</span>
<span id="cb18-123"><a href="#cb18-123" aria-hidden="true" tabindex="-1"></a>                <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb18-124"><a href="#cb18-124" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="st">"center"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-125"><a href="#cb18-125" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">background =</span> <span class="st">"#2c3e50"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-126"><a href="#cb18-126" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-127"><a href="#cb18-127" aria-hidden="true" tabindex="-1"></a>  <span class="fu">footnote</span>(<span class="at">general =</span> <span class="st">"NewJeans is the focus of this analysis."</span>)</span>
<span id="cb18-128"><a href="#cb18-128" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-129"><a href="#cb18-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-130"><a href="#cb18-130" aria-hidden="true" tabindex="-1"></a>**Total: 58 title tracks**</span>
<span id="cb18-131"><a href="#cb18-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-132"><a href="#cb18-132" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb18-133"><a href="#cb18-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-134"><a href="#cb18-134" aria-hidden="true" tabindex="-1"></a><span class="fu">## Full Corpus Explorer</span></span>
<span id="cb18-135"><a href="#cb18-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-136"><a href="#cb18-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r full-table}</span></span>
<span id="cb18-137"><a href="#cb18-137" aria-hidden="true" tabindex="-1"></a>df_display <span class="ot">&lt;-</span> df_combined <span class="sc">%&gt;%</span></span>
<span id="cb18-138"><a href="#cb18-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb18-139"><a href="#cb18-139" aria-hidden="true" tabindex="-1"></a>    Group,</span>
<span id="cb18-140"><a href="#cb18-140" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Track Name</span><span class="st">`</span> <span class="ot">=</span> Track.Name,</span>
<span id="cb18-141"><a href="#cb18-141" aria-hidden="true" tabindex="-1"></a>    Tempo,</span>
<span id="cb18-142"><a href="#cb18-142" aria-hidden="true" tabindex="-1"></a>    Energy,</span>
<span id="cb18-143"><a href="#cb18-143" aria-hidden="true" tabindex="-1"></a>    Danceability,</span>
<span id="cb18-144"><a href="#cb18-144" aria-hidden="true" tabindex="-1"></a>    Acousticness,</span>
<span id="cb18-145"><a href="#cb18-145" aria-hidden="true" tabindex="-1"></a>    Loudness,</span>
<span id="cb18-146"><a href="#cb18-146" aria-hidden="true" tabindex="-1"></a>    Valence</span>
<span id="cb18-147"><a href="#cb18-147" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-148"><a href="#cb18-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-149"><a href="#cb18-149" aria-hidden="true" tabindex="-1"></a>    <span class="at">Acousticness =</span> <span class="fu">round</span>(Acousticness, <span class="dv">3</span>),</span>
<span id="cb18-150"><a href="#cb18-150" aria-hidden="true" tabindex="-1"></a>    <span class="at">Energy =</span> <span class="fu">round</span>(Energy, <span class="dv">3</span>),</span>
<span id="cb18-151"><a href="#cb18-151" aria-hidden="true" tabindex="-1"></a>    <span class="at">Danceability =</span> <span class="fu">round</span>(Danceability, <span class="dv">3</span>),</span>
<span id="cb18-152"><a href="#cb18-152" aria-hidden="true" tabindex="-1"></a>    <span class="at">Valence =</span> <span class="fu">round</span>(Valence, <span class="dv">3</span>),</span>
<span id="cb18-153"><a href="#cb18-153" aria-hidden="true" tabindex="-1"></a>    <span class="at">Loudness =</span> <span class="fu">round</span>(Loudness, <span class="dv">1</span>),</span>
<span id="cb18-154"><a href="#cb18-154" aria-hidden="true" tabindex="-1"></a>    <span class="at">Tempo =</span> <span class="fu">round</span>(Tempo, <span class="dv">1</span>)</span>
<span id="cb18-155"><a href="#cb18-155" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-156"><a href="#cb18-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-157"><a href="#cb18-157" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(</span>
<span id="cb18-158"><a href="#cb18-158" aria-hidden="true" tabindex="-1"></a>  df_display,</span>
<span id="cb18-159"><a href="#cb18-159" aria-hidden="true" tabindex="-1"></a>  <span class="at">options =</span> <span class="fu">list</span>(<span class="at">pageLength =</span> <span class="dv">15</span>, <span class="at">order =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="dv">0</span>, <span class="st">'asc'</span>))),</span>
<span id="cb18-160"><a href="#cb18-160" aria-hidden="true" tabindex="-1"></a>  <span class="at">filter =</span> <span class="st">'top'</span>,</span>
<span id="cb18-161"><a href="#cb18-161" aria-hidden="true" tabindex="-1"></a>  <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb18-162"><a href="#cb18-162" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> htmltools<span class="sc">::</span>tags<span class="sc">$</span><span class="fu">caption</span>(</span>
<span id="cb18-163"><a href="#cb18-163" aria-hidden="true" tabindex="-1"></a>    <span class="at">style =</span> <span class="st">'caption-side: bottom; text-align: center;'</span>,</span>
<span id="cb18-164"><a href="#cb18-164" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Table 1: All 58 title tracks with Spotify audio features'</span></span>
<span id="cb18-165"><a href="#cb18-165" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-166"><a href="#cb18-166" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb18-167"><a href="#cb18-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatStyle</span>(</span>
<span id="cb18-168"><a href="#cb18-168" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Group'</span>,</span>
<span id="cb18-169"><a href="#cb18-169" aria-hidden="true" tabindex="-1"></a>    <span class="at">target =</span> <span class="st">'row'</span>,</span>
<span id="cb18-170"><a href="#cb18-170" aria-hidden="true" tabindex="-1"></a>    <span class="at">backgroundColor =</span> <span class="fu">styleEqual</span>(<span class="st">"NewJeans"</span>, <span class="st">"#FFF9E6"</span>)</span>
<span id="cb18-171"><a href="#cb18-171" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-172"><a href="#cb18-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-173"><a href="#cb18-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-174"><a href="#cb18-174" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb18-175"><a href="#cb18-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-176"><a href="#cb18-176" aria-hidden="true" tabindex="-1"></a><span class="fu">## Feature Comparison</span></span>
<span id="cb18-177"><a href="#cb18-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-178"><a href="#cb18-178" aria-hidden="true" tabindex="-1"></a><span class="fu">### Parallel Coordinates Plot</span></span>
<span id="cb18-179"><a href="#cb18-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-180"><a href="#cb18-180" aria-hidden="true" tabindex="-1"></a><span class="in">```{r parallel-coords, fig.width=12, fig.height=7}</span></span>
<span id="cb18-181"><a href="#cb18-181" aria-hidden="true" tabindex="-1"></a><span class="co"># average value preperation</span></span>
<span id="cb18-182"><a href="#cb18-182" aria-hidden="true" tabindex="-1"></a>df_avg <span class="ot">&lt;-</span> df_combined <span class="sc">%&gt;%</span></span>
<span id="cb18-183"><a href="#cb18-183" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Group) <span class="sc">%&gt;%</span></span>
<span id="cb18-184"><a href="#cb18-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-185"><a href="#cb18-185" aria-hidden="true" tabindex="-1"></a>    <span class="at">Acousticness =</span> <span class="fu">mean</span>(Acousticness),</span>
<span id="cb18-186"><a href="#cb18-186" aria-hidden="true" tabindex="-1"></a>    <span class="at">Energy =</span> <span class="fu">mean</span>(Energy),</span>
<span id="cb18-187"><a href="#cb18-187" aria-hidden="true" tabindex="-1"></a>    <span class="at">Tempo =</span> (<span class="fu">mean</span>(Tempo) <span class="sc">-</span> <span class="dv">60</span>) <span class="sc">/</span> <span class="dv">100</span>,  <span class="co"># 归一化 Tempo (60-160 缩放到 0-1)</span></span>
<span id="cb18-188"><a href="#cb18-188" aria-hidden="true" tabindex="-1"></a>    <span class="at">Loudness =</span> (<span class="fu">mean</span>(Loudness) <span class="sc">+</span> <span class="dv">20</span>) <span class="sc">/</span> <span class="dv">20</span>,  <span class="co"># 归一化 Loudness (-20-0 缩放到 0-1)</span></span>
<span id="cb18-189"><a href="#cb18-189" aria-hidden="true" tabindex="-1"></a>    <span class="at">Valence =</span> <span class="fu">mean</span>(Valence),</span>
<span id="cb18-190"><a href="#cb18-190" aria-hidden="true" tabindex="-1"></a>    <span class="at">Danceability =</span> <span class="fu">mean</span>(Danceability)</span>
<span id="cb18-191"><a href="#cb18-191" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-192"><a href="#cb18-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-193"><a href="#cb18-193" aria-hidden="true" tabindex="-1"></a><span class="co"># 转换为长格式用于平行坐标图</span></span>
<span id="cb18-194"><a href="#cb18-194" aria-hidden="true" tabindex="-1"></a>df_avg_long <span class="ot">&lt;-</span> df_avg <span class="sc">%&gt;%</span></span>
<span id="cb18-195"><a href="#cb18-195" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Group, <span class="at">names_to =</span> <span class="st">"Feature"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb18-196"><a href="#cb18-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-197"><a href="#cb18-197" aria-hidden="true" tabindex="-1"></a><span class="co"># feature order</span></span>
<span id="cb18-198"><a href="#cb18-198" aria-hidden="true" tabindex="-1"></a>feature_order <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Acousticness"</span>, <span class="st">"Energy"</span>, <span class="st">"Tempo"</span>, <span class="st">"Loudness"</span>, <span class="st">"Valence"</span>, <span class="st">"Danceability"</span>)</span>
<span id="cb18-199"><a href="#cb18-199" aria-hidden="true" tabindex="-1"></a>df_avg_long<span class="sc">$</span>Feature <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_avg_long<span class="sc">$</span>Feature, <span class="at">levels =</span> feature_order)</span>
<span id="cb18-200"><a href="#cb18-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-201"><a href="#cb18-201" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb18-202"><a href="#cb18-202" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_avg_long, <span class="fu">aes</span>(<span class="at">x =</span> Feature, <span class="at">y =</span> Value, <span class="at">color =</span> Group, <span class="at">group =</span> Group)) <span class="sc">+</span></span>
<span id="cb18-203"><a href="#cb18-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb18-204"><a href="#cb18-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb18-205"><a href="#cb18-205" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb18-206"><a href="#cb18-206" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NewJeans"</span> <span class="ot">=</span> <span class="st">"#E31A23"</span>,</span>
<span id="cb18-207"><a href="#cb18-207" aria-hidden="true" tabindex="-1"></a>    <span class="st">"aespa"</span> <span class="ot">=</span> <span class="st">"#1F77B4"</span>,</span>
<span id="cb18-208"><a href="#cb18-208" aria-hidden="true" tabindex="-1"></a>    <span class="st">"(G)I-DLE"</span> <span class="ot">=</span> <span class="st">"#2CA02C"</span>,</span>
<span id="cb18-209"><a href="#cb18-209" aria-hidden="true" tabindex="-1"></a>    <span class="st">"IVE"</span> <span class="ot">=</span> <span class="st">"#FF7F0E"</span>,</span>
<span id="cb18-210"><a href="#cb18-210" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LE SSERAFIM"</span> <span class="ot">=</span> <span class="st">"#9467BD"</span></span>
<span id="cb18-211"><a href="#cb18-211" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb18-212"><a href="#cb18-212" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Feature Comparison: NewJeans vs Other 4th Gen Groups"</span>,</span>
<span id="cb18-213"><a href="#cb18-213" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Each line represents the average of all songs from one group"</span>,</span>
<span id="cb18-214"><a href="#cb18-214" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Feature"</span>, <span class="at">y =</span> <span class="st">"Normalized Value (0-1)"</span>) <span class="sc">+</span></span>
<span id="cb18-215"><a href="#cb18-215" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-216"><a href="#cb18-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb18-217"><a href="#cb18-217" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb18-218"><a href="#cb18-218" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-219"><a href="#cb18-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-220"><a href="#cb18-220" aria-hidden="true" tabindex="-1"></a><span class="fu">### Exact Values</span></span>
<span id="cb18-221"><a href="#cb18-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-222"><a href="#cb18-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r exact-values}</span></span>
<span id="cb18-223"><a href="#cb18-223" aria-hidden="true" tabindex="-1"></a><span class="co"># NewJeans values</span></span>
<span id="cb18-224"><a href="#cb18-224" aria-hidden="true" tabindex="-1"></a>nj_values <span class="ot">&lt;-</span> df_avg <span class="sc">%&gt;%</span></span>
<span id="cb18-225"><a href="#cb18-225" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Group <span class="sc">==</span> <span class="st">"NewJeans"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-226"><a href="#cb18-226" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Group) <span class="sc">%&gt;%</span></span>
<span id="cb18-227"><a href="#cb18-227" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Feature"</span>, <span class="at">values_to =</span> <span class="st">"NewJeans"</span>)</span>
<span id="cb18-228"><a href="#cb18-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-229"><a href="#cb18-229" aria-hidden="true" tabindex="-1"></a><span class="co"># average values for all groups</span></span>
<span id="cb18-230"><a href="#cb18-230" aria-hidden="true" tabindex="-1"></a>all_values <span class="ot">&lt;-</span> df_avg <span class="sc">%&gt;%</span></span>
<span id="cb18-231"><a href="#cb18-231" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Group, <span class="at">names_to =</span> <span class="st">"Feature"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-232"><a href="#cb18-232" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Group, <span class="at">values_from =</span> Value)</span>
<span id="cb18-233"><a href="#cb18-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-234"><a href="#cb18-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-235"><a href="#cb18-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-236"><a href="#cb18-236" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"NEWJEANS FEATURE VALUES (Normalized 0-1)</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-237"><a href="#cb18-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-238"><a href="#cb18-238" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(nj_values)</span>
<span id="cb18-239"><a href="#cb18-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-240"><a href="#cb18-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-241"><a href="#cb18-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-242"><a href="#cb18-242" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"ALL GROUPS COMPARISON</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-243"><a href="#cb18-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-244"><a href="#cb18-244" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(all_values)</span>
<span id="cb18-245"><a href="#cb18-245" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-246"><a href="#cb18-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-247"><a href="#cb18-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-248"><a href="#cb18-248" aria-hidden="true" tabindex="-1"></a><span class="fu">### Analysis</span></span>
<span id="cb18-249"><a href="#cb18-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-250"><a href="#cb18-250" aria-hidden="true" tabindex="-1"></a>Based on the exact values above:</span>
<span id="cb18-251"><a href="#cb18-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-252"><a href="#cb18-252" aria-hidden="true" tabindex="-1"></a>**1. Acousticness = 0.249 — Highest among all groups**</span>
<span id="cb18-253"><a href="#cb18-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-254"><a href="#cb18-254" aria-hidden="true" tabindex="-1"></a>NewJeans scores significantly higher in acousticness than any other group (next closest is aespa at 0.133). This means their music relies more on organic instruments—guitars, live drums, natural reverb—rather than synthetic sounds. This is the sonic foundation of their "warm, nostalgic" Y2K aesthetic.</span>
<span id="cb18-255"><a href="#cb18-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-256"><a href="#cb18-256" aria-hidden="true" tabindex="-1"></a>**2. Energy = 0.749 — Lowest among all groups**</span>
<span id="cb18-257"><a href="#cb18-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-258"><a href="#cb18-258" aria-hidden="true" tabindex="-1"></a>While other groups range from 0.759 to 0.850, NewJeans sits at the bottom. This low energy is the source of their signature "effortless" feel. They don't need to be loud or aggressive to capture attention. The music breathes rather than pushes.</span>
<span id="cb18-259"><a href="#cb18-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-260"><a href="#cb18-260" aria-hidden="true" tabindex="-1"></a>**3. Tempo = 0.635 — Highest (tied with IVE)**</span>
<span id="cb18-261"><a href="#cb18-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-262"><a href="#cb18-262" aria-hidden="true" tabindex="-1"></a>This creates a unique paradox: **fastest tempo + lowest energy = rushing but relaxed**. The fast beat provides forward momentum, but the low energy keeps it from feeling frantic. This is the essence of "chill but danceable."</span>
<span id="cb18-263"><a href="#cb18-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-264"><a href="#cb18-264" aria-hidden="true" tabindex="-1"></a>**4. Loudness = 0.759 — Weakest among all groups**</span>
<span id="cb18-265"><a href="#cb18-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-266"><a href="#cb18-266" aria-hidden="true" tabindex="-1"></a>NewJeans is the quietest group. Their music preserves more dynamic range—quieter verses, fuller choruses—creating a more intimate, breathing listening experience. They don't need to be loud to be heard.</span>
<span id="cb18-267"><a href="#cb18-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-268"><a href="#cb18-268" aria-hidden="true" tabindex="-1"></a>**5. Valence = 0.634 — Highest (tied with LE SSERAFIM)**</span>
<span id="cb18-269"><a href="#cb18-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-270"><a href="#cb18-270" aria-hidden="true" tabindex="-1"></a>NewJeans' music feels the most positive and joyful. This high valence, combined with high acousticness, creates a warm, nostalgic emotional palette—music that sounds like a fond memory rather than a present scream.</span>
<span id="cb18-271"><a href="#cb18-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-272"><a href="#cb18-272" aria-hidden="true" tabindex="-1"></a>**6. Danceability = 0.766 — 2nd Highest (behind LE SSERAFIM at 0.805)**</span>
<span id="cb18-273"><a href="#cb18-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-274"><a href="#cb18-274" aria-hidden="true" tabindex="-1"></a>Despite having the lowest energy and quietest dynamics, NewJeans ranks second in danceability. This is the signature of **syncopated rhythm** (UK garage / 2-step influence). You can dance not because the music is loud or fast, but because the groove is infectious.</span>
<span id="cb18-275"><a href="#cb18-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-276"><a href="#cb18-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-277"><a href="#cb18-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-278"><a href="#cb18-278" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chromagram of "Hype Boy"</span></span>
<span id="cb18-279"><a href="#cb18-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-280"><a href="#cb18-280" aria-hidden="true" tabindex="-1"></a>For this analysis, I selected **"Hype Boy"** — NewJeans' debut title track and their first breakout hit. Released in July 2022, this song introduced the group's signature sound to the world and became an instant viral sensation. As a debut track that defined a group's identity, "Hype Boy" serves as an ideal case study for understanding the musical DNA that made NewJeans stand out. I chose to focus on a single representative song because each group's core style is most clearly expressed in their breakout hit, which captures the essence of what makes them unique.</span>
<span id="cb18-281"><a href="#cb18-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-282"><a href="#cb18-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{r load-chroma}</span></span>
<span id="cb18-283"><a href="#cb18-283" aria-hidden="true" tabindex="-1"></a><span class="co"># Load chromagram CSV exported from Sonic Visualiser</span></span>
<span id="cb18-284"><a href="#cb18-284" aria-hidden="true" tabindex="-1"></a>chroma_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/HBchroma.csv"</span>)</span>
<span id="cb18-285"><a href="#cb18-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-286"><a href="#cb18-286" aria-hidden="true" tabindex="-1"></a><span class="co"># Check data structure</span></span>
<span id="cb18-287"><a href="#cb18-287" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Chromagram dimensions:"</span>, <span class="fu">dim</span>(chroma_data), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-288"><a href="#cb18-288" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Column names:"</span>, <span class="fu">paste</span>(<span class="fu">names</span>(chroma_data), <span class="at">collapse=</span><span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-289"><a href="#cb18-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-290"><a href="#cb18-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-291"><a href="#cb18-291" aria-hidden="true" tabindex="-1"></a><span class="in">```{r plot-chroma, fig.width=12, fig.height=6}</span></span>
<span id="cb18-292"><a href="#cb18-292" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape data for heatmap</span></span>
<span id="cb18-293"><a href="#cb18-293" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb18-294"><a href="#cb18-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-295"><a href="#cb18-295" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify columns (assuming first column is time, columns 2-13 are pitch classes)</span></span>
<span id="cb18-296"><a href="#cb18-296" aria-hidden="true" tabindex="-1"></a>time_col <span class="ot">&lt;-</span> <span class="fu">names</span>(chroma_data)[<span class="dv">1</span>]</span>
<span id="cb18-297"><a href="#cb18-297" aria-hidden="true" tabindex="-1"></a>pitch_cols <span class="ot">&lt;-</span> <span class="fu">names</span>(chroma_data)[<span class="dv">2</span><span class="sc">:</span><span class="dv">13</span>]</span>
<span id="cb18-298"><a href="#cb18-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-299"><a href="#cb18-299" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract time and chroma matrix</span></span>
<span id="cb18-300"><a href="#cb18-300" aria-hidden="true" tabindex="-1"></a>time_points <span class="ot">&lt;-</span> chroma_data[[time_col]]</span>
<span id="cb18-301"><a href="#cb18-301" aria-hidden="true" tabindex="-1"></a>chroma_matrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(chroma_data[, pitch_cols])</span>
<span id="cb18-302"><a href="#cb18-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-303"><a href="#cb18-303" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data for ggplot</span></span>
<span id="cb18-304"><a href="#cb18-304" aria-hidden="true" tabindex="-1"></a>chroma_long <span class="ot">&lt;-</span> <span class="fu">melt</span>(chroma_matrix, <span class="at">varnames =</span> <span class="fu">c</span>(<span class="st">"time_idx"</span>, <span class="st">"pitch_idx"</span>), <span class="at">value.name =</span> <span class="st">"intensity"</span>)</span>
<span id="cb18-305"><a href="#cb18-305" aria-hidden="true" tabindex="-1"></a>chroma_long<span class="sc">$</span>time <span class="ot">&lt;-</span> time_points[chroma_long<span class="sc">$</span>time_idx]</span>
<span id="cb18-306"><a href="#cb18-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-307"><a href="#cb18-307" aria-hidden="true" tabindex="-1"></a><span class="co"># Pitch labels (C, C#, D, ..., B)</span></span>
<span id="cb18-308"><a href="#cb18-308" aria-hidden="true" tabindex="-1"></a>pitch_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"C"</span>, <span class="st">"C#"</span>, <span class="st">"D"</span>, <span class="st">"D#"</span>, <span class="st">"E"</span>, <span class="st">"F"</span>, <span class="st">"F#"</span>, <span class="st">"G"</span>, <span class="st">"G#"</span>, <span class="st">"A"</span>, <span class="st">"A#"</span>, <span class="st">"B"</span>)</span>
<span id="cb18-309"><a href="#cb18-309" aria-hidden="true" tabindex="-1"></a>chroma_long<span class="sc">$</span>pitch <span class="ot">&lt;-</span> pitch_labels[chroma_long<span class="sc">$</span>pitch_idx]</span>
<span id="cb18-310"><a href="#cb18-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-311"><a href="#cb18-311" aria-hidden="true" tabindex="-1"></a><span class="co"># Create heatmap with viridis color scale</span></span>
<span id="cb18-312"><a href="#cb18-312" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chroma_long, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> pitch, <span class="at">fill =</span> intensity)) <span class="sc">+</span></span>
<span id="cb18-313"><a href="#cb18-313" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb18-314"><a href="#cb18-314" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"viridis"</span>, <span class="at">name =</span> <span class="st">"Intensity"</span>) <span class="sc">+</span></span>
<span id="cb18-315"><a href="#cb18-315" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Chromagram: NewJeans - Hype Boy"</span>,</span>
<span id="cb18-316"><a href="#cb18-316" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Pitch class distribution over time | Even spread indicates harmonic ambiguity"</span>,</span>
<span id="cb18-317"><a href="#cb18-317" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Time (seconds)"</span>, <span class="at">y =</span> <span class="st">"Pitch Class"</span>) <span class="sc">+</span></span>
<span id="cb18-318"><a href="#cb18-318" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-319"><a href="#cb18-319" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>)</span>
<span id="cb18-320"><a href="#cb18-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-321"><a href="#cb18-321" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-322"><a href="#cb18-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-323"><a href="#cb18-323" aria-hidden="true" tabindex="-1"></a><span class="in">```{r chroma-stats}</span></span>
<span id="cb18-324"><a href="#cb18-324" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average chroma distribution</span></span>
<span id="cb18-325"><a href="#cb18-325" aria-hidden="true" tabindex="-1"></a>avg_chroma <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(chroma_matrix)</span>
<span id="cb18-326"><a href="#cb18-326" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(avg_chroma) <span class="ot">&lt;-</span> pitch_labels</span>
<span id="cb18-327"><a href="#cb18-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-328"><a href="#cb18-328" aria-hidden="true" tabindex="-1"></a><span class="co"># Find strongest pitches</span></span>
<span id="cb18-329"><a href="#cb18-329" aria-hidden="true" tabindex="-1"></a>top_pitches <span class="ot">&lt;-</span> <span class="fu">sort</span>(avg_chroma, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb18-330"><a href="#cb18-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-331"><a href="#cb18-331" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AVERAGE CHROMA INTENSITY BY PITCH</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-332"><a href="#cb18-332" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(avg_chroma, <span class="dv">3</span>))</span>
<span id="cb18-333"><a href="#cb18-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-334"><a href="#cb18-334" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Strongest pitch classes:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-335"><a href="#cb18-335" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) {</span>
<span id="cb18-336"><a href="#cb18-336" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"  "</span>, <span class="fu">names</span>(top_pitches)[i], <span class="st">": "</span>, <span class="fu">round</span>(top_pitches[i], <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb18-337"><a href="#cb18-337" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-338"><a href="#cb18-338" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-339"><a href="#cb18-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-340"><a href="#cb18-340" aria-hidden="true" tabindex="-1"></a><span class="fu">### Analysis</span></span>
<span id="cb18-341"><a href="#cb18-341" aria-hidden="true" tabindex="-1"></a>Looking at the chromagram data, three pitch classes stand out clearly: D (1.564), G (1.307), and A# (1.234). Everything else like F# at 0.165 and C# at 0.225 is much weaker. This tells us that "Hype Boy" has a clear harmonic center around D, with G and A# playing important supporting roles. What's interesting is the A#. In a typical major key, you'd expect A natural (the dominant), not A#. That flat 7th gives the song a slightly different color, not dramatically strange, but just enough to make it feel less predictable than standard pop. The other pitch classes are so low that the harmonic content feels focused and repetitive, which matches what we hear in the track: a smooth, hypnotic groove that doesn't jump around between different keys or throw in unexpected surprises. So overall, "Hype Boy" isn't harmonically complex or ambiguous, it's actually very consistent, built around a stable D-centered framework with a few carefully chosen pitches (G and A#) that give it its recognizable character.</span>
<span id="cb18-342"><a href="#cb18-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-343"><a href="#cb18-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-344"><a href="#cb18-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-345"><a href="#cb18-345" aria-hidden="true" tabindex="-1"></a><span class="fu">## Self-Similarity Matrices</span></span>
<span id="cb18-346"><a href="#cb18-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-347"><a href="#cb18-347" aria-hidden="true" tabindex="-1"></a>Self-similarity matrices (SSM) reveal how different sections of a song relate to each other. A dark diagonal line represents self-identity (a moment compared to itself). Patterns off the diagonal show repetition — for example, if the chorus sounds similar to the verse, those time regions will appear as bright blocks.</span>
<span id="cb18-348"><a href="#cb18-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-349"><a href="#cb18-349" aria-hidden="true" tabindex="-1"></a>For this analysis, I generated two SSMs for "Hype Boy": one using **chroma features** (harmonic content) and one using **MFCC features** (timbre / texture).</span>
<span id="cb18-350"><a href="#cb18-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-351"><a href="#cb18-351" aria-hidden="true" tabindex="-1"></a><span class="fu">### Chroma Self-Similarity Matrix</span></span>
<span id="cb18-352"><a href="#cb18-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-353"><a href="#cb18-353" aria-hidden="true" tabindex="-1"></a><span class="in">```{r load-chroma-ssm, fig.width=12, fig.height=10}</span></span>
<span id="cb18-354"><a href="#cb18-354" aria-hidden="true" tabindex="-1"></a><span class="co"># Load chromagram data</span></span>
<span id="cb18-355"><a href="#cb18-355" aria-hidden="true" tabindex="-1"></a>chroma_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/HBchroma.csv"</span>)</span>
<span id="cb18-356"><a href="#cb18-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-357"><a href="#cb18-357" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove time column, keep only pitch classes</span></span>
<span id="cb18-358"><a href="#cb18-358" aria-hidden="true" tabindex="-1"></a>chroma_matrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(chroma_data[, <span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb18-359"><a href="#cb18-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-360"><a href="#cb18-360" aria-hidden="true" tabindex="-1"></a><span class="co"># Downsample for visualization (keep every 4th frame to reduce size)</span></span>
<span id="cb18-361"><a href="#cb18-361" aria-hidden="true" tabindex="-1"></a><span class="co"># Original: 3860 frames, downsampled: 965 frames (still captures structure)</span></span>
<span id="cb18-362"><a href="#cb18-362" aria-hidden="true" tabindex="-1"></a>downsample_factor <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb18-363"><a href="#cb18-363" aria-hidden="true" tabindex="-1"></a>chroma_downsampled <span class="ot">&lt;-</span> chroma_matrix[<span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(chroma_matrix), downsample_factor), ]</span>
<span id="cb18-364"><a href="#cb18-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-365"><a href="#cb18-365" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute self-similarity matrix using cosine similarity (faster than correlation)</span></span>
<span id="cb18-366"><a href="#cb18-366" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(proxy)</span>
<span id="cb18-367"><a href="#cb18-367" aria-hidden="true" tabindex="-1"></a>chroma_ssm <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">dist</span>(chroma_downsampled, <span class="at">method =</span> <span class="st">"cosine"</span>))</span>
<span id="cb18-368"><a href="#cb18-368" aria-hidden="true" tabindex="-1"></a>chroma_ssm <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> chroma_ssm  <span class="co"># Convert distance to similarity</span></span>
<span id="cb18-369"><a href="#cb18-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-370"><a href="#cb18-370" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb18-371"><a href="#cb18-371" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb18-372"><a href="#cb18-372" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb18-373"><a href="#cb18-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-374"><a href="#cb18-374" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">melt</span>(chroma_ssm), <span class="fu">aes</span>(<span class="at">x =</span> Var1, <span class="at">y =</span> Var2, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb18-375"><a href="#cb18-375" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb18-376"><a href="#cb18-376" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"viridis"</span>, <span class="at">name =</span> <span class="st">"Similarity"</span>) <span class="sc">+</span></span>
<span id="cb18-377"><a href="#cb18-377" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Chroma Self-Similarity Matrix: NewJeans - Hype Boy"</span>,</span>
<span id="cb18-378"><a href="#cb18-378" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Bright blocks indicate structurally similar sections | Helps identify verse-chorus patterns"</span>,</span>
<span id="cb18-379"><a href="#cb18-379" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Time Frame (downsampled)"</span>, <span class="at">y =</span> <span class="st">"Time Frame (downsampled)"</span>) <span class="sc">+</span></span>
<span id="cb18-380"><a href="#cb18-380" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-381"><a href="#cb18-381" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb18-382"><a href="#cb18-382" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb18-383"><a href="#cb18-383" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>())</span>
<span id="cb18-384"><a href="#cb18-384" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-385"><a href="#cb18-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-386"><a href="#cb18-386" aria-hidden="true" tabindex="-1"></a><span class="fu">### MFCC Self-Similarity Matrix (Timbre)</span></span>
<span id="cb18-387"><a href="#cb18-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-388"><a href="#cb18-388" aria-hidden="true" tabindex="-1"></a><span class="in">```{r load-mfcc-ssm, fig.width=12, fig.height=10}</span></span>
<span id="cb18-389"><a href="#cb18-389" aria-hidden="true" tabindex="-1"></a><span class="co"># Load MFCC data</span></span>
<span id="cb18-390"><a href="#cb18-390" aria-hidden="true" tabindex="-1"></a>mfcc_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/HBMFCC.csv"</span>)</span>
<span id="cb18-391"><a href="#cb18-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-392"><a href="#cb18-392" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove time column, keep only MFCC bins</span></span>
<span id="cb18-393"><a href="#cb18-393" aria-hidden="true" tabindex="-1"></a>mfcc_matrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(mfcc_data[, <span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb18-394"><a href="#cb18-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-395"><a href="#cb18-395" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove constant columns (artifacts from Sonic Visualiser export)</span></span>
<span id="cb18-396"><a href="#cb18-396" aria-hidden="true" tabindex="-1"></a>mfcc_matrix <span class="ot">&lt;-</span> mfcc_matrix[, <span class="fu">apply</span>(mfcc_matrix, <span class="dv">2</span>, var) <span class="sc">&gt;</span> <span class="fl">0.1</span>]</span>
<span id="cb18-397"><a href="#cb18-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-398"><a href="#cb18-398" aria-hidden="true" tabindex="-1"></a><span class="co"># Downsample for visualization</span></span>
<span id="cb18-399"><a href="#cb18-399" aria-hidden="true" tabindex="-1"></a>downsample_factor <span class="ot">&lt;-</span> <span class="dv">8</span>  <span class="co"># MFCC has more frames, downsample more</span></span>
<span id="cb18-400"><a href="#cb18-400" aria-hidden="true" tabindex="-1"></a>mfcc_downsampled <span class="ot">&lt;-</span> mfcc_matrix[<span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(mfcc_matrix), downsample_factor), ]</span>
<span id="cb18-401"><a href="#cb18-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-402"><a href="#cb18-402" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute self-similarity matrix</span></span>
<span id="cb18-403"><a href="#cb18-403" aria-hidden="true" tabindex="-1"></a>mfcc_ssm <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">dist</span>(mfcc_downsampled, <span class="at">method =</span> <span class="st">"cosine"</span>))</span>
<span id="cb18-404"><a href="#cb18-404" aria-hidden="true" tabindex="-1"></a>mfcc_ssm <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> mfcc_ssm</span>
<span id="cb18-405"><a href="#cb18-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-406"><a href="#cb18-406" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb18-407"><a href="#cb18-407" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">melt</span>(mfcc_ssm), <span class="fu">aes</span>(<span class="at">x =</span> Var1, <span class="at">y =</span> Var2, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb18-408"><a href="#cb18-408" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb18-409"><a href="#cb18-409" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"viridis"</span>, <span class="at">name =</span> <span class="st">"Similarity"</span>) <span class="sc">+</span></span>
<span id="cb18-410"><a href="#cb18-410" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"MFCC Self-Similarity Matrix (Timbre): NewJeans - Hype Boy"</span>,</span>
<span id="cb18-411"><a href="#cb18-411" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Reveals timbral consistency and changes across the song structure"</span>,</span>
<span id="cb18-412"><a href="#cb18-412" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Time Frame (downsampled)"</span>, <span class="at">y =</span> <span class="st">"Time Frame (downsampled)"</span>) <span class="sc">+</span></span>
<span id="cb18-413"><a href="#cb18-413" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-414"><a href="#cb18-414" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb18-415"><a href="#cb18-415" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb18-416"><a href="#cb18-416" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>())</span>
<span id="cb18-417"><a href="#cb18-417" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-418"><a href="#cb18-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-419"><a href="#cb18-419" aria-hidden="true" tabindex="-1"></a><span class="fu">### Analysis</span></span>
<span id="cb18-420"><a href="#cb18-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-421"><a href="#cb18-421" aria-hidden="true" tabindex="-1"></a>**Chroma SSM (Harmonic Structure)**</span>
<span id="cb18-422"><a href="#cb18-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-423"><a href="#cb18-423" aria-hidden="true" tabindex="-1"></a>The Chroma SSM reveals strong harmonic repetition throughout "Hype Boy." The regular block patterns off the diagonal indicate that the song's chord progressions repeat in a predictable, cyclical manner. Verses and choruses share similar harmonic materials, meaning the song relies on repeated and stable chord loops rather than dramatic harmonic shifts.</span>
<span id="cb18-424"><a href="#cb18-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-425"><a href="#cb18-425" aria-hidden="true" tabindex="-1"></a>**MFCC SSM (Timbre / Texture)**</span>
<span id="cb18-426"><a href="#cb18-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-427"><a href="#cb18-427" aria-hidden="true" tabindex="-1"></a>The MFCC SSM shows highly consistent timbre across the entire track. The uniformly bright colors indicate that the song's instrumentation, vocal layering, and production texture remain stable from beginning to end. There are no sudden changes in sound design or abrupt stylistic shifts.</span>
<span id="cb18-428"><a href="#cb18-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-429"><a href="#cb18-429" aria-hidden="true" tabindex="-1"></a>Together, these two matrices reveal a deliberate production strategy. The Chroma SSM shows high structural repetition, which helps listeners remember the song quickly. The MFCC SSM shows timbral consistency, which creates a smooth, low-cognitive-load listening experience that is easy to replay.</span>
<span id="cb18-430"><a href="#cb18-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-431"><a href="#cb18-431" aria-hidden="true" tabindex="-1"></a>This combination of harmonic repetition and timbral stability produces a listening experience that feels cohesive, effortless, and loop-friendly. There is no sudden tension, no jarring contrast, and no unexpected complexity.</span>
<span id="cb18-432"><a href="#cb18-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-433"><a href="#cb18-433" aria-hidden="true" tabindex="-1"></a>**Why This Matters for "Hype Boy"**</span>
<span id="cb18-434"><a href="#cb18-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-435"><a href="#cb18-435" aria-hidden="true" tabindex="-1"></a>This balance between structural repetition and timbral stability reflects a modern production strategy where emotional continuity and replayability are prioritized over dramatic contrast. It helps explain why "Hype Boy" became widely popular: it is easy to remember, comfortable to listen to, and well-suited for streaming and short-form video platforms.</span>
<span id="cb18-436"><a href="#cb18-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-437"><a href="#cb18-437" aria-hidden="true" tabindex="-1"></a>The chroma SSM reveals strong harmonic repetition, while the MFCC SSM shows highly consistent timbre across the track. Together, these features create a smooth, cohesive, and highly memorable listening experience, which helps explain why "Hype Boy" became widely popular.</span>
<span id="cb18-438"><a href="#cb18-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-439"><a href="#cb18-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-440"><a href="#cb18-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-441"><a href="#cb18-441" aria-hidden="true" tabindex="-1"></a><span class="fu">## Tempogram Analysis</span></span>
<span id="cb18-442"><a href="#cb18-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-443"><a href="#cb18-443" aria-hidden="true" tabindex="-1"></a><span class="fu">### Novelty Curve</span></span>
<span id="cb18-444"><a href="#cb18-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-445"><a href="#cb18-445" aria-hidden="true" tabindex="-1"></a><span class="in">```{r novelty, fig.width=10, fig.height=4}</span></span>
<span id="cb18-446"><a href="#cb18-446" aria-hidden="true" tabindex="-1"></a>nf <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/HBnf.csv"</span>)</span>
<span id="cb18-447"><a href="#cb18-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-448"><a href="#cb18-448" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nf, <span class="fu">aes</span>(<span class="at">x =</span> nf[[<span class="dv">1</span>]], <span class="at">y =</span> nf[[<span class="dv">2</span>]])) <span class="sc">+</span></span>
<span id="cb18-449"><a href="#cb18-449" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb18-450"><a href="#cb18-450" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Novelty Curve"</span>, <span class="at">x =</span> <span class="st">"Time (s)"</span>, <span class="at">y =</span> <span class="st">"Novelty"</span>) <span class="sc">+</span></span>
<span id="cb18-451"><a href="#cb18-451" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb18-452"><a href="#cb18-452" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-453"><a href="#cb18-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-454"><a href="#cb18-454" aria-hidden="true" tabindex="-1"></a>The novelty function reveals the temporal distribution of structural changes throughout Hype Boy. Several prominent peaks appear around 20–40 seconds and 100–120 seconds, indicating moments of relatively stronger musical transitions. However, the curve is not dominated by dense or frequent high peaks; instead, it shows a continuous presence of smaller fluctuations across the entire track.</span>
<span id="cb18-455"><a href="#cb18-455" aria-hidden="true" tabindex="-1"></a>This suggests that the song does not rely on abrupt or high-intensity contrasts (e.g., dramatic “drops”) to create interest. Rather, it employs a gradual and layered progression, where changes in texture, instrumentation, or rhythmic density accumulate over time. As a result, the listening experience is perceived as smooth and flowing, with a sense of ongoing motion rather than interruption. This type of structural design supports sustained engagement and contributes to the song’s high replayability.</span>
<span id="cb18-456"><a href="#cb18-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-457"><a href="#cb18-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-458"><a href="#cb18-458" aria-hidden="true" tabindex="-1"></a><span class="fu">### Autocorrelation Tempogram (ACT)</span></span>
<span id="cb18-459"><a href="#cb18-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-460"><a href="#cb18-460" aria-hidden="true" tabindex="-1"></a><span class="in">```{r act, fig.width=10, fig.height=5}</span></span>
<span id="cb18-461"><a href="#cb18-461" aria-hidden="true" tabindex="-1"></a>act <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/HBact.csv"</span>)</span>
<span id="cb18-462"><a href="#cb18-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-463"><a href="#cb18-463" aria-hidden="true" tabindex="-1"></a>act_matrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(act[, <span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb18-464"><a href="#cb18-464" aria-hidden="true" tabindex="-1"></a>act_fill_range <span class="ot">&lt;-</span> <span class="fu">range</span>(act_matrix, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-465"><a href="#cb18-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-466"><a href="#cb18-466" aria-hidden="true" tabindex="-1"></a>act <span class="sc">|&gt;</span> </span>
<span id="cb18-467"><a href="#cb18-467" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="at">names_to =</span> <span class="st">"tempo"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb18-468"><a href="#cb18-468" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-469"><a href="#cb18-469" aria-hidden="true" tabindex="-1"></a>    <span class="at">tempo =</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[^0-9.]"</span>, <span class="st">""</span>, tempo)),</span>
<span id="cb18-470"><a href="#cb18-470" aria-hidden="true" tabindex="-1"></a>    <span class="at">value =</span> <span class="fu">sqrt</span>(value)</span>
<span id="cb18-471"><a href="#cb18-471" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb18-472"><a href="#cb18-472" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .data[[<span class="fu">names</span>(act)[<span class="dv">1</span>]]], <span class="at">y =</span> tempo, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb18-473"><a href="#cb18-473" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_raster</span>() <span class="sc">+</span></span>
<span id="cb18-474"><a href="#cb18-474" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="fu">c</span>(<span class="st">"reciprocal"</span>, <span class="st">"reverse"</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">50</span>, <span class="dv">350</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb18-475"><a href="#cb18-475" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">sqrt</span>(act_fill_range[<span class="dv">2</span>])), <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb18-476"><a href="#cb18-476" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time (s)"</span>, <span class="at">y =</span> <span class="st">"Tempo (BPM)"</span>) <span class="sc">+</span></span>
<span id="cb18-477"><a href="#cb18-477" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb18-478"><a href="#cb18-478" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-479"><a href="#cb18-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-480"><a href="#cb18-480" aria-hidden="true" tabindex="-1"></a>The autocorrelation tempogram highlights a stable and clearly defined periodic pulse, with the strongest energy concentrated around approximately 50 BPM, alongside its metrical multiples (e.g., 100 and 150 BPM). This indicates the presence of a consistent underlying beat that is perceptually salient to listeners.</span>
<span id="cb18-481"><a href="#cb18-481" aria-hidden="true" tabindex="-1"></a>Such a structure facilitates embodied entrainment: listeners can easily synchronize bodily movement (e.g., head nodding or swaying) with the music. At the same time, the visibility of multiple metrical layers suggests the coexistence of both primary beats and finer rhythmic subdivisions. This combination is characteristic of groove-oriented styles such as R&amp;B and UK garage, where rhythmic subtlety coexists with overall stability.</span>
<span id="cb18-482"><a href="#cb18-482" aria-hidden="true" tabindex="-1"></a>In Hype Boy, this results in a rhythmic feel that is not forceful or aggressive, but instead light, elastic, and naturally engaging. The groove is strong without being overwhelming, encouraging repeated listening through physical familiarity and comfort.</span>
<span id="cb18-483"><a href="#cb18-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-484"><a href="#cb18-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-485"><a href="#cb18-485" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fourier Tempogram (DFT)</span></span>
<span id="cb18-486"><a href="#cb18-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-487"><a href="#cb18-487" aria-hidden="true" tabindex="-1"></a><span class="in">```{r dft, fig.width=10, fig.height=5}</span></span>
<span id="cb18-488"><a href="#cb18-488" aria-hidden="true" tabindex="-1"></a>dft <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/HBDFT.csv"</span>)</span>
<span id="cb18-489"><a href="#cb18-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-490"><a href="#cb18-490" aria-hidden="true" tabindex="-1"></a>fill_range <span class="ot">&lt;-</span> <span class="fu">range</span>(dft[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   </span>
<span id="cb18-491"><a href="#cb18-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-492"><a href="#cb18-492" aria-hidden="true" tabindex="-1"></a>dft <span class="sc">|&gt;</span> </span>
<span id="cb18-493"><a href="#cb18-493" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="at">names_to =</span> <span class="st">"tempo"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb18-494"><a href="#cb18-494" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-495"><a href="#cb18-495" aria-hidden="true" tabindex="-1"></a>    <span class="at">tempo =</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[^0-9.]"</span>, <span class="st">""</span>, tempo)),</span>
<span id="cb18-496"><a href="#cb18-496" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> .data[[<span class="fu">names</span>(dft)[<span class="dv">1</span>]]]</span>
<span id="cb18-497"><a href="#cb18-497" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb18-498"><a href="#cb18-498" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> tempo, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb18-499"><a href="#cb18-499" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_raster</span>() <span class="sc">+</span></span>
<span id="cb18-500"><a href="#cb18-500" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"inferno"</span>, <span class="at">limits =</span> fill_range) <span class="sc">+</span></span>
<span id="cb18-501"><a href="#cb18-501" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb18-502"><a href="#cb18-502" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-503"><a href="#cb18-503" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-504"><a href="#cb18-504" aria-hidden="true" tabindex="-1"></a>The Fourier tempogram further emphasizes the periodic organization of rhythmic elements in the track. Distinct horizontal bands are visible around several tempo-related frequency regions (e.g., approximately 150, 250, and 400), indicating strong and persistent periodicities.</span>
<span id="cb18-505"><a href="#cb18-505" aria-hidden="true" tabindex="-1"></a>These patterns demonstrate that the rhythmic structure is not random or densely layered, but rather organized into clear, repeating cycles. Notably, the intensity of these bands increases in specific sections (again around 20–40 seconds and 100–115 seconds), suggesting moments where rhythmic energy is selectively reinforced.</span>
<span id="cb18-506"><a href="#cb18-506" aria-hidden="true" tabindex="-1"></a>This indicates that the song’s “hook” is not solely melodic but also rhythmic. The listener is not only remembering a tune, but also internalizing a recurring rhythmic pattern. Such periodic clarity enhances memorability while maintaining a sense of continuity, avoiding the need for abrupt structural contrasts.</span>
<span id="cb18-507"><a href="#cb18-507" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-508"><a href="#cb18-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-509"><a href="#cb18-509" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretation</span></span>
<span id="cb18-510"><a href="#cb18-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-511"><a href="#cb18-511" aria-hidden="true" tabindex="-1"></a>Taken together, these three representations suggest that Hype Boy is built upon a foundation of rhythmic stability combined with gradual, fine-grained variation. The novelty function shows that structural change is distributed and controlled rather than explosive; the autocorrelation tempogram reveals a steady and easily internalized pulse; and the Fourier tempogram confirms the presence of clear and repetitive rhythmic cycles.</span>
<span id="cb18-512"><a href="#cb18-512" aria-hidden="true" tabindex="-1"></a>This combination results in a listening experience that is smooth, lightweight, and highly loopable. Instead of relying on high-intensity contrasts typical of mainstream K-pop, the track emphasizes continuity, groove, and subtle evolution. From a stylistic perspective, this aligns closely with NewJeans’ broader aesthetic: understated, natural, and grounded in everyday listening contexts.</span>
<span id="cb18-513"><a href="#cb18-513" aria-hidden="true" tabindex="-1"></a>Such a design is particularly well-suited to contemporary music consumption environments, where replayability, background listening, and short-form media integration are crucial. The balance between recognizability and low perceptual load allows the track to be both distinctive and non-fatiguing, helping to explain its widespread appeal and viral succes</span>
<span id="cb18-514"><a href="#cb18-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-515"><a href="#cb18-515" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-516"><a href="#cb18-516" aria-hidden="true" tabindex="-1"></a><span class="fu">## Clustering</span></span>
<span id="cb18-517"><a href="#cb18-517" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-518"><a href="#cb18-518" aria-hidden="true" tabindex="-1"></a><span class="in">```{r clustering, fig.width=10, fig.height=6}</span></span>
<span id="cb18-519"><a href="#cb18-519" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data and display basic information</span></span>
<span id="cb18-520"><a href="#cb18-520" aria-hidden="true" tabindex="-1"></a>df_all <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'5K.csv'</span>)</span>
<span id="cb18-521"><a href="#cb18-521" aria-hidden="true" tabindex="-1"></a>df_seed <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'NJS_test.csv'</span>)</span>
<span id="cb18-522"><a href="#cb18-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-523"><a href="#cb18-523" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total songs:"</span>, <span class="fu">nrow</span>(df_all), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-524"><a href="#cb18-524" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Group distribution:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-525"><a href="#cb18-525" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(df_all<span class="sc">$</span>Artist.Name.s.))</span>
<span id="cb18-526"><a href="#cb18-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-527"><a href="#cb18-527" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract seed songs</span></span>
<span id="cb18-528"><a href="#cb18-528" aria-hidden="true" tabindex="-1"></a>seed_urls <span class="ot">&lt;-</span> df_seed[,<span class="dv">1</span>]</span>
<span id="cb18-529"><a href="#cb18-529" aria-hidden="true" tabindex="-1"></a>seed_songs <span class="ot">&lt;-</span> df_all<span class="sc">$</span>Track.Name[df_all<span class="sc">$</span>Track.URI <span class="sc">%in%</span> seed_urls]</span>
<span id="cb18-530"><a href="#cb18-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-531"><a href="#cb18-531" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Seed songs (5 NewJeans tracks):</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-532"><a href="#cb18-532" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(seed_songs)) {</span>
<span id="cb18-533"><a href="#cb18-533" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"  "</span>, i, <span class="st">". "</span>, seed_songs[i], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb18-534"><a href="#cb18-534" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-535"><a href="#cb18-535" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-536"><a href="#cb18-536" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare cleaned feature matrix</span></span>
<span id="cb18-537"><a href="#cb18-537" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb18-538"><a href="#cb18-538" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb18-539"><a href="#cb18-539" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(recipes)</span>
<span id="cb18-540"><a href="#cb18-540" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb18-541"><a href="#cb18-541" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-542"><a href="#cb18-542" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df_all <span class="sc">%&gt;%</span></span>
<span id="cb18-543"><a href="#cb18-543" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">Track Name</span><span class="st">`</span> <span class="ot">=</span> Track.Name,</span>
<span id="cb18-544"><a href="#cb18-544" aria-hidden="true" tabindex="-1"></a>         <span class="at">Artist =</span> Artist.Name.s.,</span>
<span id="cb18-545"><a href="#cb18-545" aria-hidden="true" tabindex="-1"></a>         Danceability, Energy, Loudness, Speechiness,</span>
<span id="cb18-546"><a href="#cb18-546" aria-hidden="true" tabindex="-1"></a>         Acousticness, Instrumentalness, Liveness,</span>
<span id="cb18-547"><a href="#cb18-547" aria-hidden="true" tabindex="-1"></a>         Valence, Tempo, <span class="st">`</span><span class="at">Duration (ms)</span><span class="st">`</span> <span class="ot">=</span> Duration..ms.) <span class="sc">%&gt;%</span></span>
<span id="cb18-548"><a href="#cb18-548" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-549"><a href="#cb18-549" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Track Name</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">str_trunc</span>(<span class="st">`</span><span class="at">Track Name</span><span class="st">`</span>, <span class="dv">36</span>))</span>
<span id="cb18-550"><a href="#cb18-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-551"><a href="#cb18-551" aria-hidden="true" tabindex="-1"></a>nrc_juice <span class="ot">&lt;-</span> <span class="fu">recipe</span>(</span>
<span id="cb18-552"><a href="#cb18-552" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Track Name</span><span class="st">`</span> <span class="sc">~</span> Danceability <span class="sc">+</span> Energy <span class="sc">+</span> Loudness <span class="sc">+</span> Speechiness <span class="sc">+</span></span>
<span id="cb18-553"><a href="#cb18-553" aria-hidden="true" tabindex="-1"></a>    Acousticness <span class="sc">+</span> Instrumentalness <span class="sc">+</span> Liveness <span class="sc">+</span> Valence <span class="sc">+</span> Tempo <span class="sc">+</span> <span class="st">`</span><span class="at">Duration (ms)</span><span class="st">`</span>,</span>
<span id="cb18-554"><a href="#cb18-554" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df_clean</span>
<span id="cb18-555"><a href="#cb18-555" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb18-556"><a href="#cb18-556" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_center</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb18-557"><a href="#cb18-557" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_scale</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb18-558"><a href="#cb18-558" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prep</span>(df_clean) <span class="sc">%&gt;%</span></span>
<span id="cb18-559"><a href="#cb18-559" aria-hidden="true" tabindex="-1"></a>  <span class="fu">juice</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-560"><a href="#cb18-560" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="st">"Track Name"</span>)</span>
<span id="cb18-561"><a href="#cb18-561" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-562"><a href="#cb18-562" aria-hidden="true" tabindex="-1"></a>nrc_dist <span class="ot">&lt;-</span> <span class="fu">dist</span>(nrc_juice, <span class="at">method =</span> <span class="st">"euclidean"</span>)</span>
<span id="cb18-563"><a href="#cb18-563" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-564"><a href="#cb18-564" aria-hidden="true" tabindex="-1"></a><span class="co"># Hierarchical clustering visualization</span></span>
<span id="cb18-565"><a href="#cb18-565" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb18-566"><a href="#cb18-566" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(method <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"single"</span>, <span class="st">"average"</span>, <span class="st">"complete"</span>)) {</span>
<span id="cb18-567"><a href="#cb18-567" aria-hidden="true" tabindex="-1"></a>  hc <span class="ot">&lt;-</span> <span class="fu">hclust</span>(nrc_dist, <span class="at">method =</span> method)</span>
<span id="cb18-568"><a href="#cb18-568" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(hc, <span class="at">main=</span><span class="fu">paste</span>(method, <span class="st">"linkage"</span>), <span class="at">xlab=</span><span class="st">""</span>, <span class="at">sub=</span><span class="st">""</span>, <span class="at">cex=</span><span class="fl">0.7</span>)</span>
<span id="cb18-569"><a href="#cb18-569" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-570"><a href="#cb18-570" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb18-571"><a href="#cb18-571" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-572"><a href="#cb18-572" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute distances to seed song centroid and rank songs</span></span>
<span id="cb18-573"><a href="#cb18-573" aria-hidden="true" tabindex="-1"></a>seed_indices <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">rownames</span>(nrc_juice) <span class="sc">%in%</span> <span class="fu">str_trunc</span>(seed_songs, <span class="dv">36</span>))</span>
<span id="cb18-574"><a href="#cb18-574" aria-hidden="true" tabindex="-1"></a>seed_names <span class="ot">&lt;-</span> <span class="fu">rownames</span>(nrc_juice)[seed_indices]</span>
<span id="cb18-575"><a href="#cb18-575" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-576"><a href="#cb18-576" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Found"</span>, <span class="fu">length</span>(seed_indices), <span class="st">"seed songs:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-577"><a href="#cb18-577" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(s <span class="cf">in</span> seed_names) <span class="fu">cat</span>(<span class="st">"  ✓"</span>, s, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-578"><a href="#cb18-578" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-579"><a href="#cb18-579" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">length</span>(seed_indices) <span class="sc">&gt;=</span> <span class="dv">2</span>) {</span>
<span id="cb18-580"><a href="#cb18-580" aria-hidden="true" tabindex="-1"></a>  seed_center <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(nrc_juice[seed_indices,])</span>
<span id="cb18-581"><a href="#cb18-581" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-582"><a href="#cb18-582" aria-hidden="true" tabindex="-1"></a>  distances <span class="ot">&lt;-</span> <span class="fu">apply</span>(nrc_juice, <span class="dv">1</span>, <span class="cf">function</span>(x) {</span>
<span id="cb18-583"><a href="#cb18-583" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sqrt</span>(<span class="fu">sum</span>((x <span class="sc">-</span> seed_center)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb18-584"><a href="#cb18-584" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb18-585"><a href="#cb18-585" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-586"><a href="#cb18-586" aria-hidden="true" tabindex="-1"></a>  results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-587"><a href="#cb18-587" aria-hidden="true" tabindex="-1"></a>    <span class="at">song =</span> <span class="fu">names</span>(distances),</span>
<span id="cb18-588"><a href="#cb18-588" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance =</span> distances</span>
<span id="cb18-589"><a href="#cb18-589" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-590"><a href="#cb18-590" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(distance) <span class="sc">%&gt;%</span></span>
<span id="cb18-591"><a href="#cb18-591" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">rank =</span> <span class="fu">row_number</span>())</span>
<span id="cb18-592"><a href="#cb18-592" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-593"><a href="#cb18-593" aria-hidden="true" tabindex="-1"></a>  results<span class="sc">$</span>group <span class="ot">&lt;-</span> df_clean<span class="sc">$</span>Artist[<span class="fu">match</span>(results<span class="sc">$</span>song, df_clean<span class="sc">$</span><span class="st">`</span><span class="at">Track Name</span><span class="st">`</span>)]</span>
<span id="cb18-594"><a href="#cb18-594" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-595"><a href="#cb18-595" aria-hidden="true" tabindex="-1"></a>  target_results <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb18-596"><a href="#cb18-596" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">"NewJeans"</span>, <span class="sc">!</span>song <span class="sc">%in%</span> seed_names)</span>
<span id="cb18-597"><a href="#cb18-597" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-598"><a href="#cb18-598" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(results, <span class="dv">20</span>),</span>
<span id="cb18-599"><a href="#cb18-599" aria-hidden="true" tabindex="-1"></a>               <span class="at">caption =</span> <span class="st">"Top 20 Songs Closest to Seed Tracks"</span>)</span>
<span id="cb18-600"><a href="#cb18-600" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-601"><a href="#cb18-601" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-602"><a href="#cb18-602" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-603"><a href="#cb18-603" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-604"><a href="#cb18-604" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb18-605"><a href="#cb18-605" aria-hidden="true" tabindex="-1"></a><span class="in">```{r clustering-conclusion, echo=FALSE}</span></span>
<span id="cb18-606"><a href="#cb18-606" aria-hidden="true" tabindex="-1"></a><span class="co"># Clustering Conclusion: dynamically generate summary text</span></span>
<span id="cb18-607"><a href="#cb18-607" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-608"><a href="#cb18-608" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">exists</span>(<span class="st">"first_target"</span>) <span class="sc">&amp;&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(first_target)) {</span>
<span id="cb18-609"><a href="#cb18-609" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-610"><a href="#cb18-610" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"## Clustering Conclusion</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb18-611"><a href="#cb18-611" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"This clustering analysis evaluated how well NewJeans seed songs could retrieve the rest of the group’s tracks based on audio features.</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb18-612"><a href="#cb18-612" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-613"><a href="#cb18-613" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"**Key Results:**</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-614"><a href="#cb18-614" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"  - Total NewJeans songs:"</span>, total_nj, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-615"><a href="#cb18-615" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"  - Seed songs used:"</span>, <span class="fu">length</span>(seed_indices), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-616"><a href="#cb18-616" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"  - Remaining target songs to find:"</span>, total_nj <span class="sc">-</span> <span class="fu">length</span>(seed_indices), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-617"><a href="#cb18-617" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"  - Number of target songs found in top 10 closest matches:"</span>, </span>
<span id="cb18-618"><a href="#cb18-618" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(results<span class="sc">$</span>group[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="sc">==</span> <span class="st">"NewJeans"</span> <span class="sc">&amp;</span> <span class="sc">!</span>results<span class="sc">$</span>song[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="sc">%in%</span> seed_names), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-619"><a href="#cb18-619" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"  - Number of target songs found in top 20 closest matches:"</span>, </span>
<span id="cb18-620"><a href="#cb18-620" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(results<span class="sc">$</span>group[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>] <span class="sc">==</span> <span class="st">"NewJeans"</span> <span class="sc">&amp;</span> <span class="sc">!</span>results<span class="sc">$</span>song[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>] <span class="sc">%in%</span> seed_names), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb18-621"><a href="#cb18-621" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-622"><a href="#cb18-622" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"**Interpretation:**</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-623"><a href="#cb18-623" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"The model demonstrates moderate ability to identify NewJeans tracks based on audio features alone. While some target songs appear among the closest matches early on, overall recall is limited. This suggests that although NewJeans tracks share distinctive characteristics, their audio feature space partially overlaps with other 4th generation K-pop groups, making precise clustering challenging.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb18-624"><a href="#cb18-624" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-625"><a href="#cb18-625" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-626"><a href="#cb18-626" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-627"><a href="#cb18-627" aria-hidden="true" tabindex="-1"></a>The model shows moderate ability to identify NewJeans songs. The first correct retrieval appears relatively early, but overall recall remains limited. This suggests that while NewJeans songs share some common audio features, their feature space overlaps substantially with other K-pop groups, making precise clustering challenging.</span>
<span id="cb18-628"><a href="#cb18-628" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-629"><a href="#cb18-629" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary and Conclusion</span></span>
<span id="cb18-630"><a href="#cb18-630" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-631"><a href="#cb18-631" aria-hidden="true" tabindex="-1"></a>This computational analysis of NewJeans and other 4th generation K-pop girl groups provides several key insights into why NewJeans achieved rapid popularity despite debuting with minimal promotion.</span>
<span id="cb18-632"><a href="#cb18-632" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-633"><a href="#cb18-633" aria-hidden="true" tabindex="-1"></a>**Corpus-Level Observations:**  </span>
<span id="cb18-634"><a href="#cb18-634" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Across 58 title tracks from five groups, NewJeans stands out for its high acousticness, moderate energy, and elevated danceability.  </span>
<span id="cb18-635"><a href="#cb18-635" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Their music balances organic instrumentation (guitars, natural reverb) with approachable tempos, creating a warm, nostalgic, and effortlessly engaging sonic identity.  </span>
<span id="cb18-636"><a href="#cb18-636" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Compared to peers, NewJeans occupies a distinctive feature space that emphasizes groove and subtle rhythmic complexity rather than loud, high-energy dynamics.  </span>
<span id="cb18-637"><a href="#cb18-637" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-638"><a href="#cb18-638" aria-hidden="true" tabindex="-1"></a>**Track-Level Analyses:**  </span>
<span id="cb18-639"><a href="#cb18-639" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Chromagram of "Hype Boy"** shows a stable harmonic center around D, with supporting pitches G and A# adding color without introducing unpredictability.  </span>
<span id="cb18-640"><a href="#cb18-640" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Self-Similarity Matrices (SSMs)** reveal high structural repetition and timbral consistency, indicating deliberate production choices that favor replayability and listener comfort.  </span>
<span id="cb18-641"><a href="#cb18-641" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Tempogram Analysis** demonstrates rhythmic stability:  </span>
<span id="cb18-642"><a href="#cb18-642" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>The novelty curve shows gradual structural changes rather than abrupt contrasts.  </span>
<span id="cb18-643"><a href="#cb18-643" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Autocorrelation tempograms highlight a clear underlying beat and its metrical multiples, promoting embodied entrainment.  </span>
<span id="cb18-644"><a href="#cb18-644" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Fourier tempograms emphasize recurring rhythmic cycles that reinforce memorability without relying on melodic hooks alone.  </span>
<span id="cb18-645"><a href="#cb18-645" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-646"><a href="#cb18-646" aria-hidden="true" tabindex="-1"></a>**Clustering Insights:**  </span>
<span id="cb18-647"><a href="#cb18-647" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Using audio feature clustering, the model successfully identifies NewJeans seed songs and ranks them closely among other tracks.  </span>
<span id="cb18-648"><a href="#cb18-648" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>While the first correct retrieval appears early, overall recall is moderate, indicating that although NewJeans shares some features with other groups, their combination of acoustic warmth, moderate energy, and rhythmic subtlety is distinctive enough to be recognized computationally.  </span>
<span id="cb18-649"><a href="#cb18-649" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-650"><a href="#cb18-650" aria-hidden="true" tabindex="-1"></a>**Overall Conclusion:**  </span>
<span id="cb18-651"><a href="#cb18-651" aria-hidden="true" tabindex="-1"></a>NewJeans’ meteoric rise appears rooted in a carefully calibrated musical identity: their tracks are stylistically cohesive, rhythmically clear, harmonically stable, and emotionally warm. These qualities make the music easily recognizable, comfortable to listen to repeatedly, and highly engaging across streaming and short-form media platforms. From a computational perspective, their audio features position them uniquely among 4th generation girl groups, offering a plausible explanation for their rapid success and cultural impact.  </span>
<span id="cb18-652"><a href="#cb18-652" aria-hidden="true" tabindex="-1"></a>---</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>